#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"
#include "constants/opponents_frlg.h"

#define TRAINER_NONE                          0
#define TRAINER_SAWYER_1                      1
#define TRAINER_GRUNT_AQUA_HIDEOUT_1          2
#define TRAINER_GRUNT_AQUA_HIDEOUT_2          3
#define TRAINER_GRUNT_AQUA_HIDEOUT_3          4
#define TRAINER_GRUNT_AQUA_HIDEOUT_4          5
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_1       6
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_2       7
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_3       8
#define TRAINER_GABRIELLE_1                   9
#define TRAINER_GRUNT_PETALBURG_WOODS        10
#define TRAINER_MARCEL                       11
#define TRAINER_ALBERTO                      12
#define TRAINER_ED                           13
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_4      14
#define TRAINER_DECLAN                       15
#define TRAINER_GRUNT_RUSTURF_TUNNEL         16
#define TRAINER_GRUNT_WEATHER_INST_1         17
#define TRAINER_GRUNT_WEATHER_INST_2         18
#define TRAINER_GRUNT_WEATHER_INST_3         19
#define TRAINER_GRUNT_MUSEUM_1               20
#define TRAINER_GRUNT_MUSEUM_2               21
#define TRAINER_GRUNT_SPACE_CENTER_1         22
#define TRAINER_GRUNT_MT_PYRE_1              23
#define TRAINER_GRUNT_MT_PYRE_2              24
#define TRAINER_GRUNT_MT_PYRE_3              25
#define TRAINER_GRUNT_WEATHER_INST_4         26
#define TRAINER_GRUNT_AQUA_HIDEOUT_5         27
#define TRAINER_GRUNT_AQUA_HIDEOUT_6         28
#define TRAINER_FREDRICK                     29
#define TRAINER_MATT                         30
#define TRAINER_ZANDER                       31
#define TRAINER_SHELLY_WEATHER_INSTITUTE     32
#define TRAINER_SHELLY_SEAFLOOR_CAVERN       33
#define TRAINER_ARCHIE                       34
#define TRAINER_LEAH                         35
#define TRAINER_DAISY                        36
#define TRAINER_ROSE_1                       37
#define TRAINER_FELIX                        38
#define TRAINER_VIOLET                       39
#define TRAINER_ROSE_2                       40
#define TRAINER_ROSE_3                       41
#define TRAINER_ROSE_4                       42
#define TRAINER_ROSE_5                       43
#define TRAINER_DUSTY_1                      44
#define TRAINER_CHIP                         45
#define TRAINER_FOSTER                       46
#define TRAINER_DUSTY_2                      47
#define TRAINER_DUSTY_3                      48
#define TRAINER_DUSTY_4                      49
#define TRAINER_DUSTY_5                      50
#define TRAINER_GABBY_AND_TY_1               51
#define TRAINER_GABBY_AND_TY_2               52
#define TRAINER_GABBY_AND_TY_3               53
#define TRAINER_GABBY_AND_TY_4               54
#define TRAINER_GABBY_AND_TY_5               55
#define TRAINER_GABBY_AND_TY_6               56
#define TRAINER_LOLA_1                       57
#define TRAINER_AUSTINA                      58
#define TRAINER_GWEN                         59
#define TRAINER_LOLA_2                       60
#define TRAINER_LOLA_3                       61
#define TRAINER_LOLA_4                       62
#define TRAINER_LOLA_5                       63
#define TRAINER_RICKY_1                      64
#define TRAINER_SIMON                        65
#define TRAINER_CHARLIE                      66
#define TRAINER_RICKY_2                      67
#define TRAINER_RICKY_3                      68
#define TRAINER_RICKY_4                      69
#define TRAINER_RICKY_5                      70
#define TRAINER_RANDALL                      71
#define TRAINER_PARKER                       72
#define TRAINER_GEORGE                       73
#define TRAINER_BERKE                        74
#define TRAINER_BRAXTON                      75
#define TRAINER_VINCENT                      76
#define TRAINER_LEROY                        77
#define TRAINER_WILTON_1                     78
#define TRAINER_EDGAR                        79
#define TRAINER_ALBERT                       80
#define TRAINER_SAMUEL                       81
#define TRAINER_VITO                         82
#define TRAINER_OWEN                         83
#define TRAINER_WILTON_2                     84
#define TRAINER_WILTON_3                     85
#define TRAINER_WILTON_4                     86
#define TRAINER_WILTON_5                     87
#define TRAINER_WARREN                       88
#define TRAINER_MARY                         89
#define TRAINER_ALEXIA                       90
#define TRAINER_JODY                         91
#define TRAINER_WENDY                        92
#define TRAINER_KEIRA                        93
#define TRAINER_BROOKE_1                     94
#define TRAINER_JENNIFER                     95
#define TRAINER_HOPE                         96
#define TRAINER_SHANNON                      97
#define TRAINER_MICHELLE                     98
#define TRAINER_CAROLINE                     99
#define TRAINER_JULIE                       100
#define TRAINER_BROOKE_2                    101
#define TRAINER_BROOKE_3                    102
#define TRAINER_BROOKE_4                    103
#define TRAINER_BROOKE_5                    104
#define TRAINER_PATRICIA                    105
#define TRAINER_KINDRA                      106
#define TRAINER_TAMMY                       107
#define TRAINER_VALERIE_1                   108
#define TRAINER_TASHA                       109
#define TRAINER_VALERIE_2                   110
#define TRAINER_VALERIE_3                   111
#define TRAINER_VALERIE_4                   112
#define TRAINER_VALERIE_5                   113
#define TRAINER_CINDY_1                     114
#define TRAINER_DAPHNE                      115
#define TRAINER_GRUNT_SPACE_CENTER_2        116
#define TRAINER_CINDY_2                     117
#define TRAINER_BRIANNA                     118
#define TRAINER_NAOMI                       119
#define TRAINER_CINDY_3                     120
#define TRAINER_CINDY_4                     121
#define TRAINER_CINDY_5                     122
#define TRAINER_CINDY_6                     123
#define TRAINER_MELISSA                     124
#define TRAINER_SHEILA                      125
#define TRAINER_SHIRLEY                     126
#define TRAINER_JESSICA_1                   127
#define TRAINER_CONNIE                      128
#define TRAINER_BRIDGET                     129
#define TRAINER_OLIVIA                      130
#define TRAINER_TIFFANY                     131
#define TRAINER_JESSICA_2                   132
#define TRAINER_JESSICA_3                   133
#define TRAINER_JESSICA_4                   134
#define TRAINER_JESSICA_5                   135
#define TRAINER_WINSTON_1                   136
#define TRAINER_MOLLIE                      137
#define TRAINER_GARRET                      138
#define TRAINER_WINSTON_2                   139
#define TRAINER_WINSTON_3                   140
#define TRAINER_WINSTON_4                   141
#define TRAINER_WINSTON_5                   142
#define TRAINER_STEVE_1                     143
#define TRAINER_THALIA_1                    144
#define TRAINER_MARK                        145
#define TRAINER_GRUNT_MT_CHIMNEY_1          146
#define TRAINER_STEVE_2                     147
#define TRAINER_STEVE_3                     148
#define TRAINER_STEVE_4                     149
#define TRAINER_STEVE_5                     150
#define TRAINER_LUIS                        151
#define TRAINER_DOMINIK                     152
#define TRAINER_DOUGLAS                     153
#define TRAINER_DARRIN                      154
#define TRAINER_TONY_1                      155
#define TRAINER_JEROME                      156
#define TRAINER_MATTHEW                     157
#define TRAINER_DAVID                       158
#define TRAINER_SPENCER                     159
#define TRAINER_ROLAND                      160
#define TRAINER_NOLEN                       161
#define TRAINER_STAN                        162
#define TRAINER_BARRY                       163
#define TRAINER_DEAN                        164
#define TRAINER_RODNEY                      165
#define TRAINER_RICHARD                     166
#define TRAINER_HERMAN                      167
#define TRAINER_SANTIAGO                    168
#define TRAINER_GILBERT                     169
#define TRAINER_FRANKLIN                    170
#define TRAINER_KEVIN                       171
#define TRAINER_JACK                        172
#define TRAINER_DUDLEY                      173
#define TRAINER_CHAD                        174
#define TRAINER_TONY_2                      175
#define TRAINER_TONY_3                      176
#define TRAINER_TONY_4                      177
#define TRAINER_TONY_5                      178
#define TRAINER_TAKAO                       179
#define TRAINER_HITOSHI                     180
#define TRAINER_KIYO                        181
#define TRAINER_KOICHI                      182
#define TRAINER_NOB_1                       183
#define TRAINER_NOB_2                       184
#define TRAINER_NOB_3                       185
#define TRAINER_NOB_4                       186
#define TRAINER_NOB_5                       187
#define TRAINER_YUJI                        188
#define TRAINER_DAISUKE                     189
#define TRAINER_ATSUSHI                     190
#define TRAINER_KIRK                        191
#define TRAINER_GRUNT_AQUA_HIDEOUT_7        192
#define TRAINER_GRUNT_AQUA_HIDEOUT_8        193
#define TRAINER_SHAWN                       194
#define TRAINER_FERNANDO_1                  195
#define TRAINER_DALTON_1                    196
#define TRAINER_DALTON_2                    197
#define TRAINER_DALTON_3                    198
#define TRAINER_DALTON_4                    199
#define TRAINER_DALTON_5                    200
#define TRAINER_COLE                        201
#define TRAINER_JEFF                        202
#define TRAINER_AXLE                        203
#define TRAINER_JACE                        204
#define TRAINER_KEEGAN                      205
#define TRAINER_BERNIE_1                    206
#define TRAINER_BERNIE_2                    207
#define TRAINER_BERNIE_3                    208
#define TRAINER_BERNIE_4                    209
#define TRAINER_BERNIE_5                    210
#define TRAINER_DREW                        211
#define TRAINER_BEAU                        212
#define TRAINER_LARRY                       213
#define TRAINER_SHANE                       214
#define TRAINER_JUSTIN                      215
#define TRAINER_ETHAN_1                     216
#define TRAINER_AUTUMN                      217
#define TRAINER_TRAVIS                      218
#define TRAINER_ETHAN_2                     219
#define TRAINER_ETHAN_3                     220
#define TRAINER_ETHAN_4                     221
#define TRAINER_ETHAN_5                     222
#define TRAINER_BRENT                       223
#define TRAINER_DONALD                      224
#define TRAINER_TAYLOR                      225
#define TRAINER_JEFFREY_1                   226
#define TRAINER_DEREK                       227
#define TRAINER_JEFFREY_2                   228
#define TRAINER_JEFFREY_3                   229
#define TRAINER_JEFFREY_4                   230
#define TRAINER_JEFFREY_5                   231
#define TRAINER_EDWARD                      232
#define TRAINER_PRESTON                     233
#define TRAINER_VIRGIL                      234
#define TRAINER_BLAKE                       235
#define TRAINER_WILLIAM                     236
#define TRAINER_JOSHUA                      237
#define TRAINER_CAMERON_1                   238
#define TRAINER_CAMERON_2                   239
#define TRAINER_CAMERON_3                   240
#define TRAINER_CAMERON_4                   241
#define TRAINER_CAMERON_5                   242
#define TRAINER_JACLYN                      243
#define TRAINER_HANNAH                      244
#define TRAINER_SAMANTHA                    245
#define TRAINER_MAURA                       246
#define TRAINER_KAYLA                       247
#define TRAINER_ALEXIS                      248
#define TRAINER_JACKI_1                     249
#define TRAINER_JACKI_2                     250
#define TRAINER_JACKI_3                     251
#define TRAINER_JACKI_4                     252
#define TRAINER_JACKI_5                     253
#define TRAINER_WALTER_1                    254
#define TRAINER_MICAH                       255
#define TRAINER_THOMAS                      256
#define TRAINER_WALTER_2                    257
#define TRAINER_WALTER_3                    258
#define TRAINER_WALTER_4                    259
#define TRAINER_WALTER_5                    260
#define TRAINER_SIDNEY                      261
#define TRAINER_PHOEBE                      262
#define TRAINER_GLACIA                      263
#define TRAINER_DRAKE                       264
#define TRAINER_ROXANNE_1                   265
#define TRAINER_BRAWLY_1                    266
#define TRAINER_WATTSON_1                   267
#define TRAINER_FLANNERY_1                  268
#define TRAINER_NORMAN_1                    269
#define TRAINER_WINONA_1                    270
#define TRAINER_TATE_AND_LIZA_1             271
#define TRAINER_WALLACE_1                   272
#define TRAINER_JUAN_1                      273
#define TRAINER_JERRY_1                     274
#define TRAINER_TED                         275
#define TRAINER_PAUL                        276
#define TRAINER_JERRY_2                     277
#define TRAINER_JERRY_3                     278
#define TRAINER_JERRY_4                     279
#define TRAINER_JERRY_5                     280
#define TRAINER_KAREN_1                     281
#define TRAINER_GEORGIA                     282
#define TRAINER_KAREN_2                     283
#define TRAINER_KAREN_3                     284
#define TRAINER_KAREN_4                     285
#define TRAINER_KAREN_5                     286
#define TRAINER_KATE_AND_JOY                287
#define TRAINER_ANNA_AND_MEG_1              288
#define TRAINER_ANNA_AND_MEG_2              289
#define TRAINER_ANNA_AND_MEG_3              290
#define TRAINER_ANNA_AND_MEG_4              291
#define TRAINER_ANNA_AND_MEG_5              292
#define TRAINER_VICTOR                      293
#define TRAINER_MIGUEL_1                    294
#define TRAINER_COLTON                      295
#define TRAINER_MIGUEL_2                    296
#define TRAINER_MIGUEL_3                    297
#define TRAINER_MIGUEL_4                    298
#define TRAINER_MIGUEL_5                    299
#define TRAINER_VICTORIA                    300
#define TRAINER_VANESSA                     301
#define TRAINER_BETHANY                     302
#define TRAINER_ISABEL_1                    303
#define TRAINER_ISABEL_2                    304
#define TRAINER_ISABEL_3                    305
#define TRAINER_ISABEL_4                    306
#define TRAINER_ISABEL_5                    307
#define TRAINER_TIMOTHY_1                   308
#define TRAINER_TIMOTHY_2                   309
#define TRAINER_TIMOTHY_3                   310
#define TRAINER_TIMOTHY_4                   311
#define TRAINER_TIMOTHY_5                   312
#define TRAINER_VICKY                       313
#define TRAINER_SHELBY_1                    314
#define TRAINER_SHELBY_2                    315
#define TRAINER_SHELBY_3                    316
#define TRAINER_SHELBY_4                    317
#define TRAINER_SHELBY_5                    318
#define TRAINER_CALVIN_1                    319
#define TRAINER_BILLY                       320
#define TRAINER_JOSH                        321
#define TRAINER_TOMMY                       322
#define TRAINER_JOEY                        323
#define TRAINER_BEN                         324
#define TRAINER_QUINCY                      325
#define TRAINER_KATELYNN                    326
#define TRAINER_JAYLEN                      327
#define TRAINER_DILLON                      328
#define TRAINER_CALVIN_2                    329
#define TRAINER_CALVIN_3                    330
#define TRAINER_CALVIN_4                    331
#define TRAINER_CALVIN_5                    332
#define TRAINER_EDDIE                       333
#define TRAINER_ALLEN                       334
#define TRAINER_TIMMY                       335
#define TRAINER_STEVEN_1                    336
#define TRAINER_ANDREW                      337
#define TRAINER_IVAN                        338
#define TRAINER_CLAUDE                      339
#define TRAINER_ELLIOT_1                    340
#define TRAINER_NED                         341
#define TRAINER_DALE                        342
#define TRAINER_NOLAN                       343
#define TRAINER_BARNY                       344
#define TRAINER_WADE                        345
#define TRAINER_CARTER                      346
#define TRAINER_ELLIOT_2                    347
#define TRAINER_ELLIOT_3                    348
#define TRAINER_ELLIOT_4                    349
#define TRAINER_ELLIOT_5                    350
#define TRAINER_RONALD                      351
#define TRAINER_JACOB                       352
#define TRAINER_ANTHONY                     353
#define TRAINER_BENJAMIN_1                  354
#define TRAINER_BENJAMIN_2                  355
#define TRAINER_BENJAMIN_3                  356
#define TRAINER_BENJAMIN_4                  357
#define TRAINER_BENJAMIN_5                  358
#define TRAINER_ABIGAIL_1                   359
#define TRAINER_JASMINE                     360
#define TRAINER_ABIGAIL_2                   361
#define TRAINER_ABIGAIL_3                   362
#define TRAINER_ABIGAIL_4                   363
#define TRAINER_ABIGAIL_5                   364
#define TRAINER_DYLAN_1                     365
#define TRAINER_DYLAN_2                     366
#define TRAINER_DYLAN_3                     367
#define TRAINER_DYLAN_4                     368
#define TRAINER_DYLAN_5                     369
#define TRAINER_MARIA_1                     370
#define TRAINER_MARIA_2                     371
#define TRAINER_MARIA_3                     372
#define TRAINER_MARIA_4                     373
#define TRAINER_MARIA_5                     374
#define TRAINER_CAMDEN                      375
#define TRAINER_DEMETRIUS                   376
#define TRAINER_ISAIAH_1                    377
#define TRAINER_PABLO_1                     378
#define TRAINER_CHASE                       379
#define TRAINER_ISAIAH_2                    380
#define TRAINER_ISAIAH_3                    381
#define TRAINER_ISAIAH_4                    382
#define TRAINER_ISAIAH_5                    383
#define TRAINER_ISOBEL                      384
#define TRAINER_DONNY                       385
#define TRAINER_TALIA                       386
#define TRAINER_KATELYN_1                   387
#define TRAINER_ALLISON                     388
#define TRAINER_KATELYN_2                   389
#define TRAINER_KATELYN_3                   390
#define TRAINER_KATELYN_4                   391
#define TRAINER_KATELYN_5                   392
#define TRAINER_NICOLAS_1                   393
#define TRAINER_NICOLAS_2                   394
#define TRAINER_NICOLAS_3                   395
#define TRAINER_NICOLAS_4                   396
#define TRAINER_NICOLAS_5                   397
#define TRAINER_AARON                       398
#define TRAINER_PERRY                       399
#define TRAINER_HUGH                        400
#define TRAINER_PHIL                        401
#define TRAINER_JARED                       402
#define TRAINER_HUMBERTO                    403
#define TRAINER_PRESLEY                     404
#define TRAINER_EDWARDO                     405
#define TRAINER_COLIN                       406
#define TRAINER_ROBERT_1                    407
#define TRAINER_BENNY                       408
#define TRAINER_CHESTER                     409
#define TRAINER_ROBERT_2                    410
#define TRAINER_ROBERT_3                    411
#define TRAINER_ROBERT_4                    412
#define TRAINER_ROBERT_5                    413
#define TRAINER_ALEX                        414
#define TRAINER_BECK                        415
#define TRAINER_YASU                        416
#define TRAINER_TAKASHI                     417
#define TRAINER_DIANNE                      418
#define TRAINER_JANI                        419
#define TRAINER_LAO_1                       420
#define TRAINER_LUNG                        421
#define TRAINER_LAO_2                       422
#define TRAINER_LAO_3                       423
#define TRAINER_LAO_4                       424
#define TRAINER_LAO_5                       425
#define TRAINER_JOCELYN                     426
#define TRAINER_LAURA                       427
#define TRAINER_CYNDY_1                     428
#define TRAINER_CORA                        429
#define TRAINER_PAULA                       430
#define TRAINER_CYNDY_2                     431
#define TRAINER_CYNDY_3                     432
#define TRAINER_CYNDY_4                     433
#define TRAINER_CYNDY_5                     434
#define TRAINER_MADELINE_1                  435
#define TRAINER_CLARISSA                    436
#define TRAINER_ANGELICA                    437
#define TRAINER_MADELINE_2                  438
#define TRAINER_MADELINE_3                  439
#define TRAINER_MADELINE_4                  440
#define TRAINER_MADELINE_5                  441
#define TRAINER_BEVERLY                     442
#define TRAINER_IMANI                       443
#define TRAINER_KYLA                        444
#define TRAINER_DENISE                      445
#define TRAINER_BETH                        446
#define TRAINER_TARA                        447
#define TRAINER_MISSY                       448
#define TRAINER_ALICE                       449
#define TRAINER_JENNY_1                     450
#define TRAINER_GRACE                       451
#define TRAINER_TANYA                       452
#define TRAINER_SHARON                      453
#define TRAINER_NIKKI                       454
#define TRAINER_BRENDA                      455
#define TRAINER_KATIE                       456
#define TRAINER_SUSIE                       457
#define TRAINER_KARA                        458
#define TRAINER_DANA                        459
#define TRAINER_SIENNA                      460
#define TRAINER_DEBRA                       461
#define TRAINER_LINDA                       462
#define TRAINER_KAYLEE                      463
#define TRAINER_LAUREL                      464
#define TRAINER_CARLEE                      465
#define TRAINER_JENNY_2                     466
#define TRAINER_JENNY_3                     467
#define TRAINER_JENNY_4                     468
#define TRAINER_JENNY_5                     469
#define TRAINER_HEIDI                       470
#define TRAINER_BECKY                       471
#define TRAINER_CAROL                       472
#define TRAINER_NANCY                       473
#define TRAINER_MARTHA                      474
#define TRAINER_DIANA_1                     475
#define TRAINER_CEDRIC                      476
#define TRAINER_IRENE                       477
#define TRAINER_DIANA_2                     478
#define TRAINER_DIANA_3                     479
#define TRAINER_DIANA_4                     480
#define TRAINER_DIANA_5                     481
#define TRAINER_AMY_AND_LIV_1               482
#define TRAINER_AMY_AND_LIV_2               483
#define TRAINER_GINA_AND_MIA_1              484
#define TRAINER_MIU_AND_YUKI                485
#define TRAINER_AMY_AND_LIV_3               486
#define TRAINER_GINA_AND_MIA_2              487
#define TRAINER_AMY_AND_LIV_4               488
#define TRAINER_AMY_AND_LIV_5               489
#define TRAINER_AMY_AND_LIV_6               490
#define TRAINER_HUEY                        491
#define TRAINER_EDMOND                      492
#define TRAINER_ERNEST_1                    493
#define TRAINER_DWAYNE                      494
#define TRAINER_PHILLIP                     495
#define TRAINER_LEONARD                     496
#define TRAINER_DUNCAN                      497
#define TRAINER_ERNEST_2                    498
#define TRAINER_ERNEST_3                    499
#define TRAINER_ERNEST_4                    500
#define TRAINER_ERNEST_5                    501
#define TRAINER_ELI                         502
#define TRAINER_ANNIKA                      503
#define TRAINER_JAZMYN                      504
#define TRAINER_JONAS                       505
#define TRAINER_KAYLEY                      506
#define TRAINER_AURON                       507
#define TRAINER_KELVIN                      508
#define TRAINER_MARLEY                      509
#define TRAINER_REYNA                       510
#define TRAINER_HUDSON                      511
#define TRAINER_CONOR                       512
#define TRAINER_EDWIN_1                     513
#define TRAINER_HECTOR                      514
#define TRAINER_TABITHA_MOSSDEEP            515
#define TRAINER_EDWIN_2                     516
#define TRAINER_EDWIN_3                     517
#define TRAINER_EDWIN_4                     518
#define TRAINER_EDWIN_5                     519
#define TRAINER_WALLY_VR_1                  520
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP    521
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP    522
#define TRAINER_BRENDAN_ROUTE_119_MUDKIP    523
#define TRAINER_BRENDAN_ROUTE_103_TREECKO   524
#define TRAINER_BRENDAN_ROUTE_110_TREECKO   525
#define TRAINER_BRENDAN_ROUTE_119_TREECKO   526
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC   527
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC   528
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC   529
#define TRAINER_MAY_ROUTE_103_MUDKIP        530
#define TRAINER_MAY_ROUTE_110_MUDKIP        531
#define TRAINER_MAY_ROUTE_119_MUDKIP        532
#define TRAINER_MAY_ROUTE_103_TREECKO       533
#define TRAINER_MAY_ROUTE_110_TREECKO       534
#define TRAINER_MAY_ROUTE_119_TREECKO       535
#define TRAINER_MAY_ROUTE_103_TORCHIC       536
#define TRAINER_MAY_ROUTE_110_TORCHIC       537
#define TRAINER_MAY_ROUTE_119_TORCHIC       538
#define TRAINER_ISAAC_1                     539
#define TRAINER_DAVIS                       540
#define TRAINER_MITCHELL                    541
#define TRAINER_ISAAC_2                     542
#define TRAINER_ISAAC_3                     543
#define TRAINER_ISAAC_4                     544
#define TRAINER_ISAAC_5                     545
#define TRAINER_LYDIA_1                     546
#define TRAINER_HALLE                       547
#define TRAINER_GARRISON                    548
#define TRAINER_LYDIA_2                     549
#define TRAINER_LYDIA_3                     550
#define TRAINER_LYDIA_4                     551
#define TRAINER_LYDIA_5                     552
#define TRAINER_JACKSON_1                   553
#define TRAINER_LORENZO                     554
#define TRAINER_SEBASTIAN                   555
#define TRAINER_JACKSON_2                   556
#define TRAINER_JACKSON_3                   557
#define TRAINER_JACKSON_4                   558
#define TRAINER_JACKSON_5                   559
#define TRAINER_CATHERINE_1                 560
#define TRAINER_JENNA                       561
#define TRAINER_SOPHIA                      562
#define TRAINER_CATHERINE_2                 563
#define TRAINER_CATHERINE_3                 564
#define TRAINER_CATHERINE_4                 565
#define TRAINER_CATHERINE_5                 566
#define TRAINER_JULIO                       567
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5     568
#define TRAINER_GRUNT_UNUSED                569
#define TRAINER_GRUNT_MT_PYRE_4             570
#define TRAINER_GRUNT_JAGGED_PASS           571
#define TRAINER_MARC                        572
#define TRAINER_BRENDEN                     573
#define TRAINER_LILITH                      574
#define TRAINER_CRISTIAN                    575
#define TRAINER_SYLVIA                      576
#define TRAINER_LEONARDO                    577
#define TRAINER_ATHENA                      578
#define TRAINER_HARRISON                    579
#define TRAINER_GRUNT_MT_CHIMNEY_2          580
#define TRAINER_CLARENCE                    581
#define TRAINER_TERRY                       582
#define TRAINER_NATE                        583
#define TRAINER_KATHLEEN                    584
#define TRAINER_CLIFFORD                    585
#define TRAINER_NICHOLAS                    586
#define TRAINER_GRUNT_SPACE_CENTER_3        587
#define TRAINER_GRUNT_SPACE_CENTER_4        588
#define TRAINER_GRUNT_SPACE_CENTER_5        589
#define TRAINER_GRUNT_SPACE_CENTER_6        590
#define TRAINER_GRUNT_SPACE_CENTER_7        591
#define TRAINER_MACEY                       592
#define TRAINER_BRENDAN_RUSTBORO_TREECKO    593
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP     594
#define TRAINER_PAXTON                      595
#define TRAINER_ISABELLA                    596
#define TRAINER_GRUNT_WEATHER_INST_5        597
#define TRAINER_TABITHA_MT_CHIMNEY          598
#define TRAINER_JONATHAN                    599
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC    600
#define TRAINER_MAY_RUSTBORO_MUDKIP         601
#define TRAINER_MAXIE_MAGMA_HIDEOUT         602
#define TRAINER_MAXIE_MT_CHIMNEY            603
#define TRAINER_TIANA                       604
#define TRAINER_HALEY_1                     605
#define TRAINER_JANICE                      606
#define TRAINER_VIVI                        607
#define TRAINER_HALEY_2                     608
#define TRAINER_HALEY_3                     609
#define TRAINER_HALEY_4                     610
#define TRAINER_HALEY_5                     611
#define TRAINER_SALLY                       612
#define TRAINER_ROBIN                       613
#define TRAINER_ANDREA                      614
#define TRAINER_CRISSY                      615
#define TRAINER_RICK                        616
#define TRAINER_LYLE                        617
#define TRAINER_JOSE                        618
#define TRAINER_DOUG                        619
#define TRAINER_GREG                        620
#define TRAINER_KENT                        621
#define TRAINER_JAMES_1                     622
#define TRAINER_JAMES_2                     623
#define TRAINER_JAMES_3                     624
#define TRAINER_JAMES_4                     625
#define TRAINER_JAMES_5                     626
#define TRAINER_BRICE                       627
#define TRAINER_TRENT_1                     628
#define TRAINER_LENNY                       629
#define TRAINER_LUCAS_1                     630
#define TRAINER_ALAN                        631
#define TRAINER_CLARK                       632
#define TRAINER_ERIC                        633
#define TRAINER_LUCAS_2                     634
#define TRAINER_MIKE_1                      635
#define TRAINER_MIKE_2                      636
#define TRAINER_TRENT_2                     637
#define TRAINER_TRENT_3                     638
#define TRAINER_TRENT_4                     639
#define TRAINER_TRENT_5                     640
#define TRAINER_DEZ_AND_LUKE                641
#define TRAINER_LEA_AND_JED                 642
#define TRAINER_KIRA_AND_DAN_1              643
#define TRAINER_KIRA_AND_DAN_2              644
#define TRAINER_KIRA_AND_DAN_3              645
#define TRAINER_KIRA_AND_DAN_4              646
#define TRAINER_KIRA_AND_DAN_5              647
#define TRAINER_JOHANNA                     648
#define TRAINER_GERALD                      649
#define TRAINER_VIVIAN                      650
#define TRAINER_DANIELLE                    651
#define TRAINER_HIDEO                       652
#define TRAINER_KEIGO                       653
#define TRAINER_RILEY                       654
#define TRAINER_FLINT                       655
#define TRAINER_ASHLEY                      656
#define TRAINER_WALLY_MAUVILLE              657
#define TRAINER_WALLY_VR_2                  658
#define TRAINER_BRENDAN_LILYCOVE_MUDKIP     659
#define TRAINER_BRENDAN_LILYCOVE_TREECKO    660
#define TRAINER_BRENDAN_LILYCOVE_TORCHIC    661
#define TRAINER_MAY_LILYCOVE_MUDKIP         662
#define TRAINER_MAY_LILYCOVE_TREECKO        663
#define TRAINER_MAY_LILYCOVE_TORCHIC        664
#define TRAINER_JONAH                       665
#define TRAINER_HENRY                       666
#define TRAINER_ROGER                       667
#define TRAINER_ALEXA                       668
#define TRAINER_RUBEN                       669
#define TRAINER_KOJI_1                      670
#define TRAINER_WAYNE                       671
#define TRAINER_AIDAN                       672
#define TRAINER_REED                        673
#define TRAINER_TISHA                       674
#define TRAINER_TORI_AND_TIA                675
#define TRAINER_KIM_AND_IRIS                676
#define TRAINER_TYRA_AND_IVY                677
#define TRAINER_MEL_AND_PAUL                678
#define TRAINER_JOHN_AND_JAY_1              679
#define TRAINER_JOHN_AND_JAY_2              680
#define TRAINER_JOHN_AND_JAY_3              681
#define TRAINER_JOHN_AND_JAY_4              682
#define TRAINER_JOHN_AND_JAY_5              683
#define TRAINER_RELI_AND_IAN                684
#define TRAINER_LILA_AND_ROY_1              685
#define TRAINER_LILA_AND_ROY_2              686
#define TRAINER_LILA_AND_ROY_3              687
#define TRAINER_LILA_AND_ROY_4              688
#define TRAINER_LILA_AND_ROY_5              689
#define TRAINER_LISA_AND_RAY                690
#define TRAINER_CHRIS                       691
#define TRAINER_DAWSON                      692
#define TRAINER_SARAH                       693
#define TRAINER_DARIAN                      694
#define TRAINER_HAILEY                      695
#define TRAINER_CHANDLER                    696
#define TRAINER_KALEB                       697
#define TRAINER_JOSEPH                      698
#define TRAINER_ALYSSA                      699
#define TRAINER_MARCOS                      700
#define TRAINER_RHETT                       701
#define TRAINER_TYRON                       702
#define TRAINER_CELINA                      703
#define TRAINER_BIANCA                      704
#define TRAINER_HAYDEN                      705
#define TRAINER_SOPHIE                      706
#define TRAINER_COBY                        707
#define TRAINER_LAWRENCE                    708
#define TRAINER_WYATT                       709
#define TRAINER_ANGELINA                    710
#define TRAINER_KAI                         711
#define TRAINER_CHARLOTTE                   712
#define TRAINER_DEANDRE                     713
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1       714
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2       715
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3       716
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4       717
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5       718
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6       719
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7       720
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8       721
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9       722
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10      723
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11      724
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12      725
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13      726
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14      727
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15      728
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16      729
#define TRAINER_TABITHA_MAGMA_HIDEOUT       730
#define TRAINER_DARCY                       731
#define TRAINER_MAXIE_MOSSDEEP              732
#define TRAINER_PETE                        733
#define TRAINER_ISABELLE                    734
#define TRAINER_ANDRES_1                    735
#define TRAINER_JOSUE                       736
#define TRAINER_CAMRON                      737
#define TRAINER_CORY_1                      738
#define TRAINER_CAROLINA                    739
#define TRAINER_ELIJAH                      740
#define TRAINER_CELIA                       741
#define TRAINER_BRYAN                       742
#define TRAINER_BRANDEN                     743
#define TRAINER_BRYANT                      744
#define TRAINER_SHAYLA                      745
#define TRAINER_KYRA                        746
#define TRAINER_JAIDEN                      747
#define TRAINER_ALIX                        748
#define TRAINER_HELENE                      749
#define TRAINER_MARLENE                     750
#define TRAINER_DEVAN                       751
#define TRAINER_JOHNSON                     752
#define TRAINER_MELINA                      753
#define TRAINER_BRANDI                      754
#define TRAINER_AISHA                       755
#define TRAINER_MAKAYLA                     756
#define TRAINER_FABIAN                      757
#define TRAINER_DAYTON                      758
#define TRAINER_RACHEL                      759
#define TRAINER_LEONEL                      760
#define TRAINER_CALLIE                      761
#define TRAINER_CALE                        762
#define TRAINER_MYLES                       763
#define TRAINER_PAT                         764
#define TRAINER_CRISTIN_1                   765
#define TRAINER_MAY_RUSTBORO_TREECKO        766
#define TRAINER_MAY_RUSTBORO_TORCHIC        767
#define TRAINER_ROXANNE_2                   768
#define TRAINER_BRAWLY_2                    769
#define TRAINER_WATTSON_2                   770
#define TRAINER_FLANNERY_2                  771
#define TRAINER_NORMAN_2                    772
#define TRAINER_WINONA_2                    773
#define TRAINER_TATE_AND_LIZA_2             774
#define TRAINER_JUAN_2                      775
#define TRAINER_ANGELO                      776
#define TRAINER_DARIUS                      777
#define TRAINER_STEVEN_2                    778
#define TRAINER_WALLACE_2                   779
#define TRAINER_ANABEL                      780
#define TRAINER_TUCKER                      781
#define TRAINER_SPENSER                     782
#define TRAINER_GRETA                       783
#define TRAINER_NOLAND                      784
#define TRAINER_LUCY                        785
#define TRAINER_BRANDON                     786
#define TRAINER_ANDRES_2                    787
#define TRAINER_ANDRES_3                    788
#define TRAINER_ANDRES_4                    789
#define TRAINER_ANDRES_5                    790
#define TRAINER_CORY_2                      791
#define TRAINER_CORY_3                      792
#define TRAINER_CORY_4                      793
#define TRAINER_CORY_5                      794
#define TRAINER_PABLO_2                     795
#define TRAINER_PABLO_3                     796
#define TRAINER_PABLO_4                     797
#define TRAINER_PABLO_5                     798
#define TRAINER_KOJI_2                      799
#define TRAINER_KOJI_3                      800
#define TRAINER_KOJI_4                      801
#define TRAINER_KOJI_5                      802
#define TRAINER_CRISTIN_2                   803
#define TRAINER_CRISTIN_3                   804
#define TRAINER_CRISTIN_4                   805
#define TRAINER_CRISTIN_5                   806
#define TRAINER_FERNANDO_2                  807
#define TRAINER_FERNANDO_3                  808
#define TRAINER_FERNANDO_4                  809
#define TRAINER_FERNANDO_5                  810
#define TRAINER_SAWYER_2                    811
#define TRAINER_SAWYER_3                    812
#define TRAINER_SAWYER_4                    813
#define TRAINER_SAWYER_5                    814
#define TRAINER_GABRIELLE_2                 815
#define TRAINER_GABRIELLE_3                 816
#define TRAINER_GABRIELLE_4                 817
#define TRAINER_GABRIELLE_5                 818
#define TRAINER_THALIA_2                    819
#define TRAINER_THALIA_3                    820
#define TRAINER_THALIA_4                    821
#define TRAINER_THALIA_5                    822
#define TRAINER_MARIELA                     823
#define TRAINER_ALVARO                      824
#define TRAINER_EVERETT                     825
#define TRAINER_RED                         826
#define TRAINER_LEAF                        827
#define TRAINER_BRENDAN_PLACEHOLDER         828
#define TRAINER_MAY_PLACEHOLDER             829

// there is some more space here!!
// Sevii trainers and Astral Emerald expansion
#define TRAINER_SWIMMER_FEMALE_MARIA 864
#define TRAINER_SWIMMER_FEMALE_ABIGAIL 865
#define TRAINER_SWIMMER_MALE_FINN 866
#define TRAINER_SWIMMER_MALE_GARRETT 867
#define TRAINER_SWIMMER_FEMALE_AMARA 868
#define TRAINER_AROMA_LADY_NIKKI 869
#define TRAINER_AROMA_LADY_VIOLET 870
#define TRAINER_TUBER_AMIRA 871
#define TRAINER_TUBER_ALEXIS 872
#define TRAINER_SWIMMER_FEMALE_TISHA 873
#define TRAINER_TWINS_JOY_MEG 874
#define TRAINER_PAINTER_DAISY 875
#define TRAINER_PAINTER_CELINA 876
#define TRAINER_PAINTER_RAYNA 877
#define TRAINER_LADY_JACKI 878
#define TRAINER_LADY_GILLIAN 879
#define TRAINER_YOUNGSTER_DESTIN 880
#define TRAINER_SWIMMER_MALE_TOBY 881
#define TRAINER_PKMN_BREEDER_ALIZE 882
#define TRAINER_BIRD_KEEPER_MILO 883
#define TRAINER_BIRD_KEEPER_CHAZ 884
#define TRAINER_BIRD_KEEPER_HAROLD 885
#define TRAINER_FISHERMAN_TYLOR 886
#define TRAINER_SWIMMER_MALE_MYMO 887
#define TRAINER_SWIMMER_FEMALE_NICOLE 888
#define TRAINER_SIS_AND_BRO_AVA_GEB 889
#define TRAINER_PSYCHIC_JACLYN 890
#define TRAINER_AROMA_LADY_ROSE 891
#define TRAINER_JUGGLER_EDWARD 892
#define TRAINER_SWIMMER_MALE_SAMIR 893
#define TRAINER_SWIMMER_FEMALE_DENISE 894
#define TRAINER_TWINS_MIU_MIA 895
#define TRAINER_HIKER_EARL 896
#define TRAINER_RUIN_MANIAC_STANLY 897
#define TRAINER_RUIN_MANIAC_FOSTER 898
#define TRAINER_RUIN_MANIAC_LARRY 899
#define TRAINER_HIKER_DARYL 900
#define TRAINER_POKEMANIAC_HECTOR 901
#define TRAINER_PSYCHIC_DARIO 902
#define TRAINER_PSYCHIC_RODETTE 903
#define TRAINER_AROMA_LADY_MIAH 904
#define TRAINER_YOUNG_COUPLE_EVE_JON 905
#define TRAINER_JUGGLER_MASON 906
#define TRAINER_PKMN_RANGER_NICOLAS 907
#define TRAINER_PKMN_RANGER_MADELINE 908
#define TRAINER_CRUSH_GIRL_CYNDY 909
#define TRAINER_TAMER_EVAN 910
#define TRAINER_PKMN_RANGER_JACKSON 911
#define TRAINER_PKMN_RANGER_KATELYN 912
#define TRAINER_COOLTRAINER_LEROY 913
#define TRAINER_COOLTRAINER_MICHELLE 914
#define TRAINER_COOL_COUPLE_LEX_NYA 915
#define TRAINER_RUIN_MANIAC_BRANDON 916
#define TRAINER_RUIN_MANIAC_BENJAMIN 917
#define TRAINER_PAINTER_EDNA 918
#define TRAINER_GENTLEMAN_CLIFFORD 919
#define TRAINER_FISHERMAN_TOMMY 920
#define TRAINER_TEAM_ROCKET_GRUNT_42 921
#define TRAINER_TEAM_ROCKET_GRUNT_43 922
#define TRAINER_TEAM_ROCKET_GRUNT_44 923
#define TRAINER_TEAM_ROCKET_GRUNT_45 924
#define TRAINER_TEAM_ROCKET_GRUNT_46 925
#define TRAINER_TEAM_ROCKET_GRUNT_47 926
#define TRAINER_TEAM_ROCKET_GRUNT_48 927
#define TRAINER_TEAM_ROCKET_GRUNT_49 928
#define TRAINER_TEAM_ROCKET_GRUNT_50 929
#define TRAINER_TEAM_ROCKET_GRUNT_51 930
#define TRAINER_TEAM_ROCKET_ADMIN 931
#define TRAINER_TEAM_ROCKET_ADMIN_2 932
#define TRAINER_CRUSH_GIRL_SHARON 933
#define TRAINER_BIKER_GOON 934
#define TRAINER_BIKER_GOON_2 935
#define TRAINER_BIKER_GOON_3 936
#define TRAINER_BIKER_2 937
#define TRAINER_RUIN_MANIAC_LAYTON 938
#define TRAINER_BUG_CATCHER_ANTHONY 939
#define TRAINER_BUG_CATCHER_CHARLIE 940
#define TRAINER_YOUNGSTER_JOHNSON 941
#define TRAINER_BIKER_RICARDO 942
#define TRAINER_BIKER_JAREN 943
#define TRAINER_SCIENTIST_GIDEON 944
#define TRAINER_BLACK_BELT_SHEA 945
#define TRAINER_BLACK_BELT_HUGH 946
#define TRAINER_CAMPER_BRYCE 947
#define TRAINER_PICNICKER_CLAIRE 948
#define TRAINER_LADY_SELPHY 949
#define TRAINER_CRUSH_GIRL_TANYA 950
#define TRAINER_RUIN_MANIAC_LAWSON 951
#define TRAINER_PSYCHIC_LAURA 952
#define TRAINER_PKMN_BREEDER_BETHANY 953
#define TRAINER_PKMN_BREEDER_ALLISON 954
#define TRAINER_BUG_CATCHER_GARRET 955
#define TRAINER_BUG_CATCHER_JONAH 956
#define TRAINER_BUG_CATCHER_VANCE 957
#define TRAINER_YOUNGSTER_NASH 958
#define TRAINER_YOUNGSTER_CORDELL 959
#define TRAINER_LASS_DALIA 960
#define TRAINER_LASS_JOANA 961
#define TRAINER_CAMPER_RILEY 962
#define TRAINER_CRUSH_KIN_MIK_KIA 963
#define TRAINER_CRUSH_GIRL_JOCELYN 964
#define TRAINER_POKEMANIAC_MARK_2 965
#define TRAINER_PKMN_RANGER_LOGAN 966
#define TRAINER_PKMN_RANGER_BETH 967
#define TRAINER_PICNICKER_MARCY 968

/*
#define aba 970
#define aba 971
#define aba 972
#define aba 973
#define aba 974
#define aba 975
#define aba 976
#define aba 977
#define aba 978
#define aba 979
#define aba 980
#define aba 981
#define aba 982
#define aba 983
#define aba 984
#define aba 985
#define aba 986
#define aba 987
#define aba 988
#define aba 989
#define aba 990
#define aba 991
#define aba 992
#define aba 993
#define aba 994
#define aba 995
#define aba 996
#define aba 997
#define aba 998
#define aba 999
*/
// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT_EMERALD     970
#define MAX_TRAINERS_COUNT_EMERALD 970

#if IS_FRLG
#define TRAINERS_COUNT                      TRAINERS_COUNT_FRLG
#define MAX_TRAINERS_COUNT                  MAX_TRAINERS_COUNT_FRLG
#else
#define TRAINERS_COUNT                      TRAINERS_COUNT_EMERALD
#define MAX_TRAINERS_COUNT                  MAX_TRAINERS_COUNT_EMERALD
#endif
#define TRAINER_PARTNER(partner)           (MAX_TRAINERS_COUNT + partner)

#endif  // GUARD_CONSTANTS_OPPONENTS_H
