#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"
#include "constants/opponents_frlg.h"

#define TRAINER_NONE                          0
#define TRAINER_SAWYER_1                      1
#define TRAINER_GRUNT_AQUA_HIDEOUT_1          2
#define TRAINER_GRUNT_AQUA_HIDEOUT_2          3
#define TRAINER_GRUNT_AQUA_HIDEOUT_3          4
#define TRAINER_GRUNT_AQUA_HIDEOUT_4          5
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_1       6
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_2       7
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_3       8
#define TRAINER_GABRIELLE_1                   9
#define TRAINER_GRUNT_PETALBURG_WOODS        10
#define TRAINER_MARCEL                       11
#define TRAINER_ALBERTO                      12
#define TRAINER_ED                           13
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_4      14
#define TRAINER_DECLAN                       15
#define TRAINER_GRUNT_RUSTURF_TUNNEL         16
#define TRAINER_GRUNT_WEATHER_INST_1         17
#define TRAINER_GRUNT_WEATHER_INST_2         18
#define TRAINER_GRUNT_WEATHER_INST_3         19
#define TRAINER_GRUNT_MUSEUM_1               20
#define TRAINER_GRUNT_MUSEUM_2               21
#define TRAINER_GRUNT_SPACE_CENTER_1         22
#define TRAINER_GRUNT_MT_PYRE_1              23
#define TRAINER_GRUNT_MT_PYRE_2              24
#define TRAINER_GRUNT_MT_PYRE_3              25
#define TRAINER_GRUNT_WEATHER_INST_4         26
#define TRAINER_GRUNT_AQUA_HIDEOUT_5         27
#define TRAINER_GRUNT_AQUA_HIDEOUT_6         28
#define TRAINER_FREDRICK                     29
#define TRAINER_MATT                         30
#define TRAINER_ZANDER                       31
#define TRAINER_SHELLY_WEATHER_INSTITUTE     32
#define TRAINER_SHELLY_SEAFLOOR_CAVERN       33
#define TRAINER_ARCHIE                       34
#define TRAINER_LEAH                         35
#define TRAINER_DAISY                        36
#define TRAINER_ROSE_1                       37
#define TRAINER_FELIX                        38
#define TRAINER_VIOLET                       39
#define TRAINER_ROSE_2                       40
#define TRAINER_ROSE_3                       41
#define TRAINER_ROSE_4                       42
#define TRAINER_ROSE_5                       43
#define TRAINER_DUSTY_1                      44
#define TRAINER_CHIP                         45
#define TRAINER_FOSTER                       46
#define TRAINER_DUSTY_2                      47
#define TRAINER_DUSTY_3                      48
#define TRAINER_DUSTY_4                      49
#define TRAINER_DUSTY_5                      50
#define TRAINER_GABBY_AND_TY_1               51
#define TRAINER_GABBY_AND_TY_2               52
#define TRAINER_GABBY_AND_TY_3               53
#define TRAINER_GABBY_AND_TY_4               54
#define TRAINER_GABBY_AND_TY_5               55
#define TRAINER_GABBY_AND_TY_6               56
#define TRAINER_LOLA_1                       57
#define TRAINER_AUSTINA                      58
#define TRAINER_GWEN                         59
#define TRAINER_LOLA_2                       60
#define TRAINER_LOLA_3                       61
#define TRAINER_LOLA_4                       62
#define TRAINER_LOLA_5                       63
#define TRAINER_RICKY_1                      64
#define TRAINER_SIMON                        65
#define TRAINER_CHARLIE                      66
#define TRAINER_RICKY_2                      67
#define TRAINER_RICKY_3                      68
#define TRAINER_RICKY_4                      69
#define TRAINER_RICKY_5                      70
#define TRAINER_RANDALL                      71
#define TRAINER_PARKER                       72
#define TRAINER_GEORGE                       73
#define TRAINER_BERKE                        74
#define TRAINER_BRAXTON                      75
#define TRAINER_VINCENT                      76
#define TRAINER_LEROY                        77
#define TRAINER_WILTON_1                     78
#define TRAINER_EDGAR                        79
#define TRAINER_ALBERT                       80
#define TRAINER_SAMUEL                       81
#define TRAINER_VITO                         82
#define TRAINER_OWEN                         83
#define TRAINER_WILTON_2                     84
#define TRAINER_WILTON_3                     85
#define TRAINER_WILTON_4                     86
#define TRAINER_WILTON_5                     87
#define TRAINER_WARREN                       88
#define TRAINER_MARY                         89
#define TRAINER_ALEXIA                       90
#define TRAINER_JODY                         91
#define TRAINER_WENDY                        92
#define TRAINER_KEIRA                        93
#define TRAINER_BROOKE_1                     94
#define TRAINER_JENNIFER                     95
#define TRAINER_HOPE                         96
#define TRAINER_SHANNON                      97
#define TRAINER_MICHELLE                     98
#define TRAINER_CAROLINE                     99
#define TRAINER_JULIE                       100
#define TRAINER_BROOKE_2                    101
#define TRAINER_BROOKE_3                    102
#define TRAINER_BROOKE_4                    103
#define TRAINER_BROOKE_5                    104
#define TRAINER_PATRICIA                    105
#define TRAINER_KINDRA                      106
#define TRAINER_TAMMY                       107
#define TRAINER_VALERIE_1                   108
#define TRAINER_TASHA                       109
#define TRAINER_VALERIE_2                   110
#define TRAINER_VALERIE_3                   111
#define TRAINER_VALERIE_4                   112
#define TRAINER_VALERIE_5                   113
#define TRAINER_CINDY_1                     114
#define TRAINER_DAPHNE                      115
#define TRAINER_GRUNT_SPACE_CENTER_2        116
#define TRAINER_CINDY_2                     117
#define TRAINER_BRIANNA                     118
#define TRAINER_NAOMI                       119
#define TRAINER_CINDY_3                     120
#define TRAINER_CINDY_4                     121
#define TRAINER_CINDY_5                     122
#define TRAINER_CINDY_6                     123
#define TRAINER_MELISSA                     124
#define TRAINER_SHEILA                      125
#define TRAINER_SHIRLEY                     126
#define TRAINER_JESSICA_1                   127
#define TRAINER_CONNIE                      128
#define TRAINER_BRIDGET                     129
#define TRAINER_OLIVIA                      130
#define TRAINER_TIFFANY                     131
#define TRAINER_JESSICA_2                   132
#define TRAINER_JESSICA_3                   133
#define TRAINER_JESSICA_4                   134
#define TRAINER_JESSICA_5                   135
#define TRAINER_WINSTON_1                   136
#define TRAINER_MOLLIE                      137
#define TRAINER_GARRET                      138
#define TRAINER_WINSTON_2                   139
#define TRAINER_WINSTON_3                   140
#define TRAINER_WINSTON_4                   141
#define TRAINER_WINSTON_5                   142
#define TRAINER_STEVE_1                     143
#define TRAINER_THALIA_1                    144
#define TRAINER_MARK                        145
#define TRAINER_GRUNT_MT_CHIMNEY_1          146
#define TRAINER_STEVE_2                     147
#define TRAINER_STEVE_3                     148
#define TRAINER_STEVE_4                     149
#define TRAINER_STEVE_5                     150
#define TRAINER_LUIS                        151
#define TRAINER_DOMINIK                     152
#define TRAINER_DOUGLAS                     153
#define TRAINER_DARRIN                      154
#define TRAINER_TONY_1                      155
#define TRAINER_JEROME                      156
#define TRAINER_MATTHEW                     157
#define TRAINER_DAVID                       158
#define TRAINER_SPENCER                     159
#define TRAINER_ROLAND                      160
#define TRAINER_NOLEN                       161
#define TRAINER_STAN                        162
#define TRAINER_BARRY                       163
#define TRAINER_DEAN                        164
#define TRAINER_RODNEY                      165
#define TRAINER_RICHARD                     166
#define TRAINER_HERMAN                      167
#define TRAINER_SANTIAGO                    168
#define TRAINER_GILBERT                     169
#define TRAINER_FRANKLIN                    170
#define TRAINER_KEVIN                       171
#define TRAINER_JACK                        172
#define TRAINER_DUDLEY                      173
#define TRAINER_CHAD                        174
#define TRAINER_TONY_2                      175
#define TRAINER_TONY_3                      176
#define TRAINER_TONY_4                      177
#define TRAINER_TONY_5                      178
#define TRAINER_TAKAO                       179
#define TRAINER_HITOSHI                     180
#define TRAINER_KIYO                        181
#define TRAINER_KOICHI                      182
#define TRAINER_NOB_1                       183
#define TRAINER_NOB_2                       184
#define TRAINER_NOB_3                       185
#define TRAINER_NOB_4                       186
#define TRAINER_NOB_5                       187
#define TRAINER_YUJI                        188
#define TRAINER_DAISUKE                     189
#define TRAINER_ATSUSHI                     190
#define TRAINER_KIRK                        191
#define TRAINER_GRUNT_AQUA_HIDEOUT_7        192
#define TRAINER_GRUNT_AQUA_HIDEOUT_8        193
#define TRAINER_SHAWN                       194
#define TRAINER_FERNANDO_1                  195
#define TRAINER_DALTON_1                    196
#define TRAINER_DALTON_2                    197
#define TRAINER_DALTON_3                    198
#define TRAINER_DALTON_4                    199
#define TRAINER_DALTON_5                    200
#define TRAINER_COLE                        201
#define TRAINER_JEFF                        202
#define TRAINER_AXLE                        203
#define TRAINER_JACE                        204
#define TRAINER_KEEGAN                      205
#define TRAINER_BERNIE_1                    206
#define TRAINER_BERNIE_2                    207
#define TRAINER_BERNIE_3                    208
#define TRAINER_BERNIE_4                    209
#define TRAINER_BERNIE_5                    210
#define TRAINER_DREW                        211
#define TRAINER_BEAU                        212
#define TRAINER_LARRY                       213
#define TRAINER_SHANE                       214
#define TRAINER_JUSTIN                      215
#define TRAINER_ETHAN_1                     216
#define TRAINER_AUTUMN                      217
#define TRAINER_TRAVIS                      218
#define TRAINER_ETHAN_2                     219
#define TRAINER_ETHAN_3                     220
#define TRAINER_ETHAN_4                     221
#define TRAINER_ETHAN_5                     222
#define TRAINER_BRENT                       223
#define TRAINER_DONALD                      224
#define TRAINER_TAYLOR                      225
#define TRAINER_JEFFREY_1                   226
#define TRAINER_DEREK                       227
#define TRAINER_JEFFREY_2                   228
#define TRAINER_JEFFREY_3                   229
#define TRAINER_JEFFREY_4                   230
#define TRAINER_JEFFREY_5                   231
#define TRAINER_EDWARD                      232
#define TRAINER_PRESTON                     233
#define TRAINER_VIRGIL                      234
#define TRAINER_BLAKE                       235
#define TRAINER_WILLIAM                     236
#define TRAINER_JOSHUA                      237
#define TRAINER_CAMERON_1                   238
#define TRAINER_CAMERON_2                   239
#define TRAINER_CAMERON_3                   240
#define TRAINER_CAMERON_4                   241
#define TRAINER_CAMERON_5                   242
#define TRAINER_JACLYN                      243
#define TRAINER_HANNAH                      244
#define TRAINER_SAMANTHA                    245
#define TRAINER_MAURA                       246
#define TRAINER_KAYLA                       247
#define TRAINER_ALEXIS                      248
#define TRAINER_JACKI_1                     249
#define TRAINER_JACKI_2                     250
#define TRAINER_JACKI_3                     251
#define TRAINER_JACKI_4                     252
#define TRAINER_JACKI_5                     253
#define TRAINER_WALTER_1                    254
#define TRAINER_MICAH                       255
#define TRAINER_THOMAS                      256
#define TRAINER_WALTER_2                    257
#define TRAINER_WALTER_3                    258
#define TRAINER_WALTER_4                    259
#define TRAINER_WALTER_5                    260
#define TRAINER_SIDNEY                      261
#define TRAINER_PHOEBE                      262
#define TRAINER_GLACIA                      263
#define TRAINER_DRAKE                       264
#define TRAINER_ROXANNE_1                   265
#define TRAINER_BRAWLY_1                    266
#define TRAINER_JUAN_1                      267
#define TRAINER_WATTSON_1                   268
#define TRAINER_FLANNERY_1                  269
#define TRAINER_NORMAN_1                    270
#define TRAINER_WINONA_1                    271
#define TRAINER_JUAN_2                      272
#define TRAINER_TATE_AND_LIZA_1             273
#define TRAINER_WALLACE_1                   274
#define TRAINER_JERRY_1                     275
#define TRAINER_TED                         276
#define TRAINER_PAUL                        277
#define TRAINER_JERRY_2                     278
#define TRAINER_JERRY_3                     279
#define TRAINER_JERRY_4                     280
#define TRAINER_JERRY_5                     281
#define TRAINER_KAREN_1                     282
#define TRAINER_GEORGIA                     283
#define TRAINER_KAREN_2                     284
#define TRAINER_KAREN_3                     285
#define TRAINER_KAREN_4                     286
#define TRAINER_KAREN_5                     287
#define TRAINER_KATE_AND_JOY                288
#define TRAINER_ANNA_AND_MEG_1              289
#define TRAINER_ANNA_AND_MEG_2              290
#define TRAINER_ANNA_AND_MEG_3              291
#define TRAINER_ANNA_AND_MEG_4              292
#define TRAINER_ANNA_AND_MEG_5              293
#define TRAINER_VICTOR                      294
#define TRAINER_MIGUEL_1                    295
#define TRAINER_COLTON                      296
#define TRAINER_MIGUEL_2                    297
#define TRAINER_MIGUEL_3                    298
#define TRAINER_MIGUEL_4                    299
#define TRAINER_MIGUEL_5                    300
#define TRAINER_VICTORIA                    301
#define TRAINER_VANESSA                     302
#define TRAINER_BETHANY                     303
#define TRAINER_ISABEL_1                    304
#define TRAINER_ISABEL_2                    305
#define TRAINER_ISABEL_3                    306
#define TRAINER_ISABEL_4                    307
#define TRAINER_ISABEL_5                    308
#define TRAINER_TIMOTHY_1                   309
#define TRAINER_TIMOTHY_2                   310
#define TRAINER_TIMOTHY_3                   311
#define TRAINER_TIMOTHY_4                   312
#define TRAINER_TIMOTHY_5                   313
#define TRAINER_VICKY                       314
#define TRAINER_SHELBY_1                    315
#define TRAINER_SHELBY_2                    316
#define TRAINER_SHELBY_3                    317
#define TRAINER_SHELBY_4                    318
#define TRAINER_SHELBY_5                    319
#define TRAINER_CALVIN_1                    320
#define TRAINER_BILLY                       321
#define TRAINER_JOSH                        322
#define TRAINER_TOMMY                       323
#define TRAINER_JOEY                        324
#define TRAINER_BEN                         325
#define TRAINER_QUINCY                      326
#define TRAINER_KATELYNN                    327
#define TRAINER_JAYLEN                      328
#define TRAINER_DILLON                      329
#define TRAINER_CALVIN_2                    330
#define TRAINER_CALVIN_3                    331
#define TRAINER_CALVIN_4                    332
#define TRAINER_CALVIN_5                    333
#define TRAINER_EDDIE                       334
#define TRAINER_ALLEN                       335
#define TRAINER_TIMMY                       336
#define TRAINER_STEVEN_1                    337
#define TRAINER_ANDREW                      338
#define TRAINER_IVAN                        339
#define TRAINER_CLAUDE                      340
#define TRAINER_ELLIOT_1                    341
#define TRAINER_NED                         342
#define TRAINER_DALE                        343
#define TRAINER_NOLAN                       344
#define TRAINER_BARNY                       345
#define TRAINER_WADE                        346
#define TRAINER_CARTER                      347
#define TRAINER_ELLIOT_2                    348
#define TRAINER_ELLIOT_3                    349
#define TRAINER_ELLIOT_4                    350
#define TRAINER_ELLIOT_5                    351
#define TRAINER_RONALD                      352
#define TRAINER_JACOB                       353
#define TRAINER_ANTHONY                     354
#define TRAINER_BENJAMIN_1                  355
#define TRAINER_BENJAMIN_2                  356
#define TRAINER_BENJAMIN_3                  357
#define TRAINER_BENJAMIN_4                  358
#define TRAINER_BENJAMIN_5                  359
#define TRAINER_ABIGAIL_1                   360
#define TRAINER_JASMINE                     361
#define TRAINER_ABIGAIL_2                   362
#define TRAINER_ABIGAIL_3                   363
#define TRAINER_ABIGAIL_4                   364
#define TRAINER_ABIGAIL_5                   365
#define TRAINER_DYLAN_1                     366
#define TRAINER_DYLAN_2                     367
#define TRAINER_DYLAN_3                     368
#define TRAINER_DYLAN_4                     369
#define TRAINER_DYLAN_5                     370
#define TRAINER_MARIA_1                     371
#define TRAINER_MARIA_2                     372
#define TRAINER_MARIA_3                     373
#define TRAINER_MARIA_4                     374
#define TRAINER_MARIA_5                     375
#define TRAINER_CAMDEN                      376
#define TRAINER_DEMETRIUS                   377
#define TRAINER_ISAIAH_1                    378
#define TRAINER_PABLO_1                     379
#define TRAINER_CHASE                       380
#define TRAINER_ISAIAH_2                    381
#define TRAINER_ISAIAH_3                    382
#define TRAINER_ISAIAH_4                    383
#define TRAINER_ISAIAH_5                    384
#define TRAINER_ISOBEL                      385
#define TRAINER_DONNY                       386
#define TRAINER_TALIA                       387
#define TRAINER_KATELYN_1                   388
#define TRAINER_ALLISON                     389
#define TRAINER_KATELYN_2                   390
#define TRAINER_KATELYN_3                   391
#define TRAINER_KATELYN_4                   392
#define TRAINER_KATELYN_5                   393
#define TRAINER_NICOLAS_1                   394
#define TRAINER_NICOLAS_2                   395
#define TRAINER_NICOLAS_3                   396
#define TRAINER_NICOLAS_4                   397
#define TRAINER_NICOLAS_5                   398
#define TRAINER_AARON                       399
#define TRAINER_PERRY                       400
#define TRAINER_HUGH                        401
#define TRAINER_PHIL                        402
#define TRAINER_JARED                       403
#define TRAINER_HUMBERTO                    404
#define TRAINER_PRESLEY                     405
#define TRAINER_EDWARDO                     406
#define TRAINER_COLIN                       407
#define TRAINER_ROBERT_1                    408
#define TRAINER_BENNY                       409
#define TRAINER_CHESTER                     410
#define TRAINER_ROBERT_2                    411
#define TRAINER_ROBERT_3                    412
#define TRAINER_ROBERT_4                    413
#define TRAINER_ROBERT_5                    414
#define TRAINER_ALEX                        415
#define TRAINER_BECK                        416
#define TRAINER_YASU                        417
#define TRAINER_TAKASHI                     418
#define TRAINER_DIANNE                      419
#define TRAINER_JANI                        420
#define TRAINER_LAO_1                       421
#define TRAINER_LUNG                        422
#define TRAINER_LAO_2                       423
#define TRAINER_LAO_3                       424
#define TRAINER_LAO_4                       425
#define TRAINER_LAO_5                       426
#define TRAINER_JOCELYN                     427
#define TRAINER_LAURA                       428
#define TRAINER_CYNDY_1                     429
#define TRAINER_CORA                        430
#define TRAINER_PAULA                       431
#define TRAINER_CYNDY_2                     432
#define TRAINER_CYNDY_3                     433
#define TRAINER_CYNDY_4                     434
#define TRAINER_CYNDY_5                     435
#define TRAINER_MADELINE_1                  436
#define TRAINER_CLARISSA                    437
#define TRAINER_ANGELICA                    438
#define TRAINER_MADELINE_2                  439
#define TRAINER_MADELINE_3                  440
#define TRAINER_MADELINE_4                  441
#define TRAINER_MADELINE_5                  442
#define TRAINER_BEVERLY                     443
#define TRAINER_IMANI                       444
#define TRAINER_KYLA                        445
#define TRAINER_DENISE                      446
#define TRAINER_BETH                        447
#define TRAINER_TARA                        448
#define TRAINER_MISSY                       449
#define TRAINER_ALICE                       450
#define TRAINER_JENNY_1                     451
#define TRAINER_GRACE                       452
#define TRAINER_TANYA                       453
#define TRAINER_SHARON                      454
#define TRAINER_NIKKI                       455
#define TRAINER_BRENDA                      456
#define TRAINER_KATIE                       457
#define TRAINER_SUSIE                       458
#define TRAINER_KARA                        459
#define TRAINER_DANA                        460
#define TRAINER_SIENNA                      461
#define TRAINER_DEBRA                       462
#define TRAINER_LINDA                       463
#define TRAINER_KAYLEE                      464
#define TRAINER_LAUREL                      465
#define TRAINER_CARLEE                      466
#define TRAINER_JENNY_2                     467
#define TRAINER_JENNY_3                     468
#define TRAINER_JENNY_4                     469
#define TRAINER_JENNY_5                     470
#define TRAINER_HEIDI                       471
#define TRAINER_BECKY                       472
#define TRAINER_CAROL                       473
#define TRAINER_NANCY                       474
#define TRAINER_MARTHA                      475
#define TRAINER_DIANA_1                     476
#define TRAINER_CEDRIC                      477
#define TRAINER_IRENE                       478
#define TRAINER_DIANA_2                     479
#define TRAINER_DIANA_3                     480
#define TRAINER_DIANA_4                     481
#define TRAINER_DIANA_5                     482
#define TRAINER_AMY_AND_LIV_1               483
#define TRAINER_AMY_AND_LIV_2               484
#define TRAINER_GINA_AND_MIA_1              485
#define TRAINER_MIU_AND_YUKI                486
#define TRAINER_AMY_AND_LIV_3               487
#define TRAINER_GINA_AND_MIA_2              488
#define TRAINER_AMY_AND_LIV_4               489
#define TRAINER_AMY_AND_LIV_5               490
#define TRAINER_AMY_AND_LIV_6               491
#define TRAINER_HUEY                        492
#define TRAINER_EDMOND                      493
#define TRAINER_ERNEST_1                    494
#define TRAINER_DWAYNE                      495
#define TRAINER_PHILLIP                     496
#define TRAINER_LEONARD                     497
#define TRAINER_DUNCAN                      498
#define TRAINER_ERNEST_2                    499
#define TRAINER_ERNEST_3                    500
#define TRAINER_ERNEST_4                    501
#define TRAINER_ERNEST_5                    502
#define TRAINER_ELI                         503
#define TRAINER_ANNIKA                      504
#define TRAINER_JAZMYN                      505
#define TRAINER_JONAS                       506
#define TRAINER_KAYLEY                      507
#define TRAINER_AURON                       508
#define TRAINER_KELVIN                      509
#define TRAINER_MARLEY                      510
#define TRAINER_REYNA                       511
#define TRAINER_HUDSON                      512
#define TRAINER_CONOR                       513
#define TRAINER_EDWIN_1                     514
#define TRAINER_HECTOR                      515
#define TRAINER_TABITHA_MOSSDEEP            516
#define TRAINER_EDWIN_2                     517
#define TRAINER_EDWIN_3                     518
#define TRAINER_EDWIN_4                     519
#define TRAINER_EDWIN_5                     520
#define TRAINER_WALLY_VR_1                  521
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP    522
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP    523
#define TRAINER_BRENDAN_ROUTE_119_MUDKIP    524
#define TRAINER_BRENDAN_ROUTE_103_TREECKO   525
#define TRAINER_BRENDAN_ROUTE_110_TREECKO   526
#define TRAINER_BRENDAN_ROUTE_119_TREECKO   527
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC   528
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC   529
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC   530
#define TRAINER_MAY_ROUTE_103_MUDKIP        531
#define TRAINER_MAY_ROUTE_110_MUDKIP        532
#define TRAINER_MAY_ROUTE_119_MUDKIP        533
#define TRAINER_MAY_ROUTE_103_TREECKO       534
#define TRAINER_MAY_ROUTE_110_TREECKO       535
#define TRAINER_MAY_ROUTE_119_TREECKO       536
#define TRAINER_MAY_ROUTE_103_TORCHIC       537
#define TRAINER_MAY_ROUTE_110_TORCHIC       538
#define TRAINER_MAY_ROUTE_119_TORCHIC       539
#define TRAINER_ISAAC_1                     540
#define TRAINER_DAVIS                       541
#define TRAINER_MITCHELL                    542
#define TRAINER_ISAAC_2                     543
#define TRAINER_ISAAC_3                     544
#define TRAINER_ISAAC_4                     545
#define TRAINER_ISAAC_5                     546
#define TRAINER_LYDIA_1                     547
#define TRAINER_HALLE                       548
#define TRAINER_GARRISON                    549
#define TRAINER_LYDIA_2                     550
#define TRAINER_LYDIA_3                     551
#define TRAINER_LYDIA_4                     552
#define TRAINER_LYDIA_5                     553
#define TRAINER_JACKSON_1                   554
#define TRAINER_LORENZO                     555
#define TRAINER_SEBASTIAN                   556
#define TRAINER_JACKSON_2                   557
#define TRAINER_JACKSON_3                   558
#define TRAINER_JACKSON_4                   559
#define TRAINER_JACKSON_5                   560
#define TRAINER_CATHERINE_1                 561
#define TRAINER_JENNA                       562
#define TRAINER_SOPHIA                      563
#define TRAINER_CATHERINE_2                 564
#define TRAINER_CATHERINE_3                 565
#define TRAINER_CATHERINE_4                 566
#define TRAINER_CATHERINE_5                 567
#define TRAINER_JULIO                       568
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5     569
#define TRAINER_GRUNT_UNUSED                570
#define TRAINER_GRUNT_MT_PYRE_4             571
#define TRAINER_GRUNT_JAGGED_PASS           572
#define TRAINER_MARC                        573
#define TRAINER_BRENDEN                     574
#define TRAINER_LILITH                      575
#define TRAINER_CRISTIAN                    576
#define TRAINER_SYLVIA                      577
#define TRAINER_LEONARDO                    578
#define TRAINER_ATHENA                      579
#define TRAINER_HARRISON                    580
#define TRAINER_GRUNT_MT_CHIMNEY_2          581
#define TRAINER_CLARENCE                    582
#define TRAINER_TERRY                       583
#define TRAINER_NATE                        584
#define TRAINER_KATHLEEN                    585
#define TRAINER_CLIFFORD                    586
#define TRAINER_NICHOLAS                    587
#define TRAINER_GRUNT_SPACE_CENTER_3        588
#define TRAINER_GRUNT_SPACE_CENTER_4        589
#define TRAINER_GRUNT_SPACE_CENTER_5        590
#define TRAINER_GRUNT_SPACE_CENTER_6        591
#define TRAINER_GRUNT_SPACE_CENTER_7        592
#define TRAINER_MACEY                       593
#define TRAINER_BRENDAN_RUSTBORO_TREECKO    594
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP     595
#define TRAINER_PAXTON                      596
#define TRAINER_ISABELLA                    597
#define TRAINER_GRUNT_WEATHER_INST_5        598
#define TRAINER_TABITHA_MT_CHIMNEY          599
#define TRAINER_JONATHAN                    600
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC    601
#define TRAINER_MAY_RUSTBORO_MUDKIP         602
#define TRAINER_MAXIE_MAGMA_HIDEOUT         603
#define TRAINER_MAXIE_MT_CHIMNEY            604
#define TRAINER_TIANA                       605
#define TRAINER_HALEY_1                     606
#define TRAINER_JANICE                      607
#define TRAINER_VIVI                        608
#define TRAINER_HALEY_2                     609
#define TRAINER_HALEY_3                     610
#define TRAINER_HALEY_4                     611
#define TRAINER_HALEY_5                     612
#define TRAINER_SALLY                       613
#define TRAINER_ROBIN                       614
#define TRAINER_ANDREA                      615
#define TRAINER_CRISSY                      616
#define TRAINER_RICK                        617
#define TRAINER_LYLE                        618
#define TRAINER_JOSE                        619
#define TRAINER_DOUG                        620
#define TRAINER_GREG                        621
#define TRAINER_KENT                        622
#define TRAINER_JAMES_1                     623
#define TRAINER_JAMES_2                     624
#define TRAINER_JAMES_3                     625
#define TRAINER_JAMES_4                     626
#define TRAINER_JAMES_5                     627
#define TRAINER_BRICE                       628
#define TRAINER_TRENT_1                     629
#define TRAINER_LENNY                       630
#define TRAINER_LUCAS_1                     631
#define TRAINER_ALAN                        632
#define TRAINER_CLARK                       633
#define TRAINER_ERIC                        634
#define TRAINER_LUCAS_2                     635
#define TRAINER_MIKE_1                      636
#define TRAINER_MIKE_2                      637
#define TRAINER_TRENT_2                     638
#define TRAINER_TRENT_3                     639
#define TRAINER_TRENT_4                     640
#define TRAINER_TRENT_5                     641
#define TRAINER_DEZ_AND_LUKE                642
#define TRAINER_LEA_AND_JED                 643
#define TRAINER_KIRA_AND_DAN_1              644
#define TRAINER_KIRA_AND_DAN_2              645
#define TRAINER_KIRA_AND_DAN_3              646
#define TRAINER_KIRA_AND_DAN_4              647
#define TRAINER_KIRA_AND_DAN_5              648
#define TRAINER_JOHANNA                     649
#define TRAINER_GERALD                      650
#define TRAINER_VIVIAN                      651
#define TRAINER_DANIELLE                    652
#define TRAINER_HIDEO                       653
#define TRAINER_KEIGO                       654
#define TRAINER_RILEY                       655
#define TRAINER_FLINT                       656
#define TRAINER_ASHLEY                      657
#define TRAINER_WALLY_MAUVILLE              658
#define TRAINER_WALLY_VR_2                  659
#define TRAINER_BRENDAN_LILYCOVE_MUDKIP     660
#define TRAINER_BRENDAN_LILYCOVE_TREECKO    661
#define TRAINER_BRENDAN_LILYCOVE_TORCHIC    662
#define TRAINER_MAY_LILYCOVE_MUDKIP         663
#define TRAINER_MAY_LILYCOVE_TREECKO        664
#define TRAINER_MAY_LILYCOVE_TORCHIC        665
#define TRAINER_JONAH                       666
#define TRAINER_HENRY                       667
#define TRAINER_ROGER                       668
#define TRAINER_ALEXA                       669
#define TRAINER_RUBEN                       670
#define TRAINER_KOJI_1                      671
#define TRAINER_WAYNE                       672
#define TRAINER_AIDAN                       673
#define TRAINER_REED                        674
#define TRAINER_TISHA                       675
#define TRAINER_TORI_AND_TIA                676
#define TRAINER_KIM_AND_IRIS                677
#define TRAINER_TYRA_AND_IVY                678
#define TRAINER_MEL_AND_PAUL                679
#define TRAINER_JOHN_AND_JAY_1              680
#define TRAINER_JOHN_AND_JAY_2              681
#define TRAINER_JOHN_AND_JAY_3              682
#define TRAINER_JOHN_AND_JAY_4              683
#define TRAINER_JOHN_AND_JAY_5              684
#define TRAINER_RELI_AND_IAN                685
#define TRAINER_LILA_AND_ROY_1              686
#define TRAINER_LILA_AND_ROY_2              687
#define TRAINER_LILA_AND_ROY_3              688
#define TRAINER_LILA_AND_ROY_4              689
#define TRAINER_LILA_AND_ROY_5              690
#define TRAINER_LISA_AND_RAY                691
#define TRAINER_CHRIS                       692
#define TRAINER_DAWSON                      693
#define TRAINER_SARAH                       694
#define TRAINER_DARIAN                      695
#define TRAINER_HAILEY                      696
#define TRAINER_CHANDLER                    697
#define TRAINER_KALEB                       698
#define TRAINER_JOSEPH                      699
#define TRAINER_ALYSSA                      700
#define TRAINER_MARCOS                      701
#define TRAINER_RHETT                       702
#define TRAINER_TYRON                       703
#define TRAINER_CELINA                      704
#define TRAINER_BIANCA                      705
#define TRAINER_HAYDEN                      706
#define TRAINER_SOPHIE                      707
#define TRAINER_COBY                        708
#define TRAINER_LAWRENCE                    709
#define TRAINER_WYATT                       710
#define TRAINER_ANGELINA                    711
#define TRAINER_KAI                         712
#define TRAINER_CHARLOTTE                   713
#define TRAINER_DEANDRE                     714
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1       715
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2       716
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3       717
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4       718
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5       719
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6       720
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7       721
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8       722
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9       723
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10      724
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11      725
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12      726
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13      727
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14      728
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15      729
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16      730
#define TRAINER_TABITHA_MAGMA_HIDEOUT       731
#define TRAINER_DARCY                       732
#define TRAINER_MAXIE_MOSSDEEP              733
#define TRAINER_PETE                        734
#define TRAINER_ISABELLE                    735
#define TRAINER_ANDRES_1                    736
#define TRAINER_JOSUE                       737
#define TRAINER_CAMRON                      738
#define TRAINER_CORY_1                      739
#define TRAINER_CAROLINA                    740
#define TRAINER_ELIJAH                      741
#define TRAINER_CELIA                       742
#define TRAINER_BRYAN                       743
#define TRAINER_BRANDEN                     744
#define TRAINER_BRYANT                      745
#define TRAINER_SHAYLA                      746
#define TRAINER_KYRA                        747
#define TRAINER_JAIDEN                      748
#define TRAINER_ALIX                        749
#define TRAINER_HELENE                      750
#define TRAINER_MARLENE                     751
#define TRAINER_DEVAN                       752
#define TRAINER_JOHNSON                     753
#define TRAINER_MELINA                      754
#define TRAINER_BRANDI                      755
#define TRAINER_AISHA                       756
#define TRAINER_MAKAYLA                     757
#define TRAINER_FABIAN                      758
#define TRAINER_DAYTON                      759
#define TRAINER_RACHEL                      760
#define TRAINER_LEONEL                      761
#define TRAINER_CALLIE                      762
#define TRAINER_CALE                        763
#define TRAINER_MYLES                       764
#define TRAINER_PAT                         765
#define TRAINER_CRISTIN_1                   766
#define TRAINER_MAY_RUSTBORO_TREECKO        767
#define TRAINER_MAY_RUSTBORO_TORCHIC        768
#define TRAINER_ROXANNE_2                   769
#define TRAINER_BRAWLY_2                    770
#define TRAINER_WATTSON_2                   771
#define TRAINER_FLANNERY_2                  772
#define TRAINER_NORMAN_2                    773
#define TRAINER_WINONA_2                    774
#define TRAINER_TATE_AND_LIZA_2             775
#define TRAINER_JUAN_3                      776
#define TRAINER_ANGELO                      777
#define TRAINER_DARIUS                      778
#define TRAINER_STEVEN_2                    779
#define TRAINER_WALLACE_2                   780
#define TRAINER_ANABEL                      781
#define TRAINER_TUCKER                      782
#define TRAINER_SPENSER                     783
#define TRAINER_GRETA                       784
#define TRAINER_NOLAND                      785
#define TRAINER_LUCY                        786
#define TRAINER_BRANDON                     787
#define TRAINER_ANDRES_2                    788
#define TRAINER_ANDRES_3                    789
#define TRAINER_ANDRES_4                    790
#define TRAINER_ANDRES_5                    791
#define TRAINER_CORY_2                      792
#define TRAINER_CORY_3                      793
#define TRAINER_CORY_4                      794
#define TRAINER_CORY_5                      795
#define TRAINER_PABLO_2                     796
#define TRAINER_PABLO_3                     797
#define TRAINER_PABLO_4                     798
#define TRAINER_PABLO_5                     799
#define TRAINER_KOJI_2                      800
#define TRAINER_KOJI_3                      801
#define TRAINER_KOJI_4                      802
#define TRAINER_KOJI_5                      803
#define TRAINER_CRISTIN_2                   804
#define TRAINER_CRISTIN_3                   805
#define TRAINER_CRISTIN_4                   806
#define TRAINER_CRISTIN_5                   807
#define TRAINER_FERNANDO_2                  808
#define TRAINER_FERNANDO_3                  809
#define TRAINER_FERNANDO_4                  810
#define TRAINER_FERNANDO_5                  811
#define TRAINER_SAWYER_2                    812
#define TRAINER_SAWYER_3                    813
#define TRAINER_SAWYER_4                    814
#define TRAINER_SAWYER_5                    815
#define TRAINER_GABRIELLE_2                 816
#define TRAINER_GABRIELLE_3                 817
#define TRAINER_GABRIELLE_4                 818
#define TRAINER_GABRIELLE_5                 819
#define TRAINER_THALIA_2                    820
#define TRAINER_THALIA_3                    821
#define TRAINER_THALIA_4                    822
#define TRAINER_THALIA_5                    823
#define TRAINER_MARIELA                     824
#define TRAINER_ALVARO                      825
#define TRAINER_EVERETT                     826
#define TRAINER_RED                         827
#define TRAINER_LEAF                        828
#define TRAINER_BRENDAN_PLACEHOLDER         829
#define TRAINER_MAY_PLACEHOLDER             830

// there is some more space here!!
// Sevii trainers and Astral Emerald expansion
#define TRAINER_SWIMMER_FEMALE_MARIA 864
#define TRAINER_SWIMMER_FEMALE_ABIGAIL 865
#define TRAINER_SWIMMER_MALE_FINN 866
#define TRAINER_SWIMMER_MALE_GARRETT 867
#define TRAINER_SWIMMER_FEMALE_AMARA 868
#define TRAINER_AROMA_LADY_NIKKI 869
#define TRAINER_AROMA_LADY_VIOLET 870
#define TRAINER_TUBER_AMIRA 871
#define TRAINER_TUBER_ALEXIS 872
#define TRAINER_SWIMMER_FEMALE_TISHA 873
#define TRAINER_TWINS_JOY_MEG 874
#define TRAINER_PAINTER_DAISY 875
#define TRAINER_PAINTER_CELINA 876
#define TRAINER_PAINTER_RAYNA 877
#define TRAINER_LADY_JACKI 878
#define TRAINER_LADY_GILLIAN 879
#define TRAINER_YOUNGSTER_DESTIN 880
#define TRAINER_SWIMMER_MALE_TOBY 881
#define TRAINER_PKMN_BREEDER_ALIZE 882
#define TRAINER_BIRD_KEEPER_MILO 883
#define TRAINER_BIRD_KEEPER_CHAZ 884
#define TRAINER_BIRD_KEEPER_HAROLD 885
#define TRAINER_FISHERMAN_TYLOR 886
#define TRAINER_SWIMMER_MALE_MYMO 887
#define TRAINER_SWIMMER_FEMALE_NICOLE 888
#define TRAINER_SIS_AND_BRO_AVA_GEB 889
#define TRAINER_PSYCHIC_JACLYN 890
#define TRAINER_AROMA_LADY_ROSE 891
#define TRAINER_JUGGLER_EDWARD 892
#define TRAINER_SWIMMER_MALE_SAMIR 893
#define TRAINER_SWIMMER_FEMALE_DENISE 894
#define TRAINER_TWINS_MIU_MIA 895
#define TRAINER_HIKER_EARL 896
#define TRAINER_RUIN_MANIAC_STANLY 897
#define TRAINER_RUIN_MANIAC_FOSTER 898
#define TRAINER_RUIN_MANIAC_LARRY 899
#define TRAINER_HIKER_DARYL 900
#define TRAINER_POKEMANIAC_HECTOR 901
#define TRAINER_PSYCHIC_DARIO 902
#define TRAINER_PSYCHIC_RODETTE 903
#define TRAINER_AROMA_LADY_MIAH 904
#define TRAINER_YOUNG_COUPLE_EVE_JON 905
#define TRAINER_JUGGLER_MASON 906
#define TRAINER_PKMN_RANGER_NICOLAS 907
#define TRAINER_PKMN_RANGER_MADELINE 908
#define TRAINER_CRUSH_GIRL_CYNDY 909
#define TRAINER_TAMER_EVAN 910
#define TRAINER_PKMN_RANGER_JACKSON 911
#define TRAINER_PKMN_RANGER_KATELYN 912
#define TRAINER_COOLTRAINER_LEROY 913
#define TRAINER_COOLTRAINER_MICHELLE 914
#define TRAINER_COOL_COUPLE_LEX_NYA 915
#define TRAINER_RUIN_MANIAC_BRANDON 916
#define TRAINER_RUIN_MANIAC_BENJAMIN 917
#define TRAINER_PAINTER_EDNA 918
#define TRAINER_GENTLEMAN_CLIFFORD 919
#define TRAINER_FISHERMAN_TOMMY 920
#define TRAINER_TEAM_ROCKET_GRUNT_42 921
#define TRAINER_TEAM_ROCKET_GRUNT_43 922
#define TRAINER_TEAM_ROCKET_GRUNT_44 923
#define TRAINER_TEAM_ROCKET_GRUNT_45 924
#define TRAINER_TEAM_ROCKET_GRUNT_46 925
#define TRAINER_TEAM_ROCKET_GRUNT_47 926
#define TRAINER_TEAM_ROCKET_GRUNT_48 927
#define TRAINER_TEAM_ROCKET_GRUNT_49 928
#define TRAINER_TEAM_ROCKET_GRUNT_50 929
#define TRAINER_TEAM_ROCKET_GRUNT_51 930
#define TRAINER_TEAM_ROCKET_ADMIN 931
#define TRAINER_TEAM_ROCKET_ADMIN_2 932
#define TRAINER_CRUSH_GIRL_SHARON 933
#define TRAINER_BIKER_GOON 934
#define TRAINER_BIKER_GOON_2 935
#define TRAINER_BIKER_GOON_3 936
#define TRAINER_BIKER_2 937
#define TRAINER_RUIN_MANIAC_LAYTON 938
#define TRAINER_BUG_CATCHER_ANTHONY 939
#define TRAINER_BUG_CATCHER_CHARLIE 940
#define TRAINER_YOUNGSTER_JOHNSON 941
#define TRAINER_BIKER_RICARDO 942
#define TRAINER_BIKER_JAREN 943
#define TRAINER_SCIENTIST_GIDEON 944
#define TRAINER_BLACK_BELT_SHEA 945
#define TRAINER_BLACK_BELT_HUGH 946
#define TRAINER_CAMPER_BRYCE 947
#define TRAINER_PICNICKER_CLAIRE 948
#define TRAINER_LADY_SELPHY 949
#define TRAINER_CRUSH_GIRL_TANYA 950
#define TRAINER_RUIN_MANIAC_LAWSON 951
#define TRAINER_PSYCHIC_LAURA 952
#define TRAINER_PKMN_BREEDER_BETHANY 953
#define TRAINER_PKMN_BREEDER_ALLISON 954
#define TRAINER_BUG_CATCHER_GARRET 955
#define TRAINER_BUG_CATCHER_JONAH 956
#define TRAINER_BUG_CATCHER_VANCE 957
#define TRAINER_YOUNGSTER_NASH 958
#define TRAINER_YOUNGSTER_CORDELL 959
#define TRAINER_LASS_DALIA 960
#define TRAINER_LASS_JOANA 961
#define TRAINER_CAMPER_RILEY 962
#define TRAINER_CRUSH_KIN_MIK_KIA 963
#define TRAINER_CRUSH_GIRL_JOCELYN 964
#define TRAINER_POKEMANIAC_MARK_2 965
#define TRAINER_PKMN_RANGER_LOGAN 966
#define TRAINER_PKMN_RANGER_BETH 967
#define TRAINER_PICNICKER_MARCY 968

/*
#define aba 970
#define aba 971
#define aba 972
#define aba 973
#define aba 974
#define aba 975
#define aba 976
#define aba 977
#define aba 978
#define aba 979
#define aba 980
#define aba 981
#define aba 982
#define aba 983
#define aba 984
#define aba 985
#define aba 986
#define aba 987
#define aba 988
#define aba 989
#define aba 990
#define aba 991
#define aba 992
#define aba 993
#define aba 994
#define aba 995
#define aba 996
#define aba 997
#define aba 998
#define aba 999
*/
// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT_EMERALD     970
#define MAX_TRAINERS_COUNT_EMERALD 970

#if IS_FRLG
#define TRAINERS_COUNT                      TRAINERS_COUNT_FRLG
#define MAX_TRAINERS_COUNT                  MAX_TRAINERS_COUNT_FRLG
#else
#define TRAINERS_COUNT                      TRAINERS_COUNT_EMERALD
#define MAX_TRAINERS_COUNT                  MAX_TRAINERS_COUNT_EMERALD
#endif
#define TRAINER_PARTNER(partner)           (MAX_TRAINERS_COUNT + partner)

#endif  // GUARD_CONSTANTS_OPPONENTS_H
