MtEmber_RubyPath_B4F_MapScripts::
	.byte 0

MtEmber_RubyPath_B4F_EventScript_BrailleABC::
	lockall
	waitbuttonpress
	releaseall
	end

MtEmber_RubyPath_B4F_EventScript_BrailleGHI::
	lockall
	waitbuttonpress
	releaseall
	end

MtEmber_RubyPath_B4F_EventScript_BrailleMNO::
	lockall
	waitbuttonpress
	releaseall
	end

MtEmber_RubyPath_B4F_EventScript_BrailleTUV::
	lockall
	waitbuttonpress
	releaseall
	end

MtEmber_RubyPath_B4F_EventScript_BrailleDEF::
	lockall
	waitbuttonpress
	releaseall
	end

MtEmber_RubyPath_B4F_EventScript_BrailleJKL::
	lockall
	waitbuttonpress
	releaseall
	end

MtEmber_RubyPath_B4F_EventScript_BraillePQRS::
	lockall
	waitbuttonpress
	releaseall
	end

MtEmber_RubyPath_B4F_EventScript_BrailleWXYZ::
	lockall
	waitbuttonpress
	releaseall
	end

MtEmber_RubyPath_B4F_EventScript_BraillePeriod::
	lockall
	waitbuttonpress
	releaseall
	end

MtEmber_RubyPath_B4F_EventScript_BrailleComma::
	lockall
	waitbuttonpress
	releaseall
	end
