Common_EventScript_FindItem::
	callnative GetItemBallIdAndAmountFromTemplate
	finditem VAR_RESULT VAR_0x8009
	end


BoonIsland_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

KinIsland_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

FloeIsland_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

FloeIsland_EventScript_ItemStardust::
	finditem ITEM_STARDUST
	end

KnotIsland_KindleRoad_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

KnotIsland_KindleRoad_EventScript_ItemMaxRepel::
	finditem ITEM_MAX_REPEL
	end

KnotIsland_KindleRoad_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

ChronoIsland_Meadow_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

ChronoIsland_Meadow_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

ChronoIsland_MemorialPillar_EventScript_ItemMetalCoat::
	finditem ITEM_METAL_COAT
	end

FortuneIsland_OutcastIsland_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

FortuneIsland_WaterPath_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

FortuneIsland_WaterPath_EventScript_ItemDragonScale::
	finditem ITEM_DRAGON_SCALE
	end

FortuneIsland_RuinValley_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

FortuneIsland_RuinValley_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

FortuneIsland_RuinValley_EventScript_ItemSunStone::
	finditem ITEM_SUN_STONE
	end

QuestIsland_SevaultCanyon_EventScript_ItemKingsRock::
	finditem ITEM_KINGS_ROCK
	end

QuestIsland_SevaultCanyon_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

QuestIsland_SevaultCanyon_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

KinIsland_BerryForest_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

KinIsland_BerryForest_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

KinIsland_BerryForest_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

MtEmber_Exterior_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

MtEmber_Exterior_EventScript_ItemFireStone::
	finditem ITEM_FIRE_STONE
	end

MtEmber_Exterior_EventScript_ItemDireHit::
	finditem ITEM_DIRE_HIT
	end

FloeIsland_IcefallCave_1F_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

FloeIsland_IcefallCave_1F_EventScript_ItemHM07::
	finditem ITEM_HM07
	end

FloeIsland_IcefallCave_B1F_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

FloeIsland_IcefallCave_B1F_EventScript_ItemNeverMeltIce::
	finditem ITEM_NEVER_MELT_ICE
	end

ChronoIsland_Warehouse_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

ChronoIsland_Warehouse_EventScript_ItemTM36::
	finditem ITEM_TM36
	end

ChronoIsland_Warehouse_EventScript_ItemPearl::
	finditem ITEM_PEARL
	end

ChronoIsland_Warehouse_EventScript_ItemUpGrade::
	finditem ITEM_UP_GRADE
	end

ChronoIsland_LostCave_Room10_EventScript_ItemSilkScarf::
	finditem ITEM_SILK_SCARF
	end

ChronoIsland_LostCave_Room11_EventScript_ItemLaxIncense::
	finditem ITEM_LAX_INCENSE
	end

ChronoIsland_LostCave_Room12_EventScript_ItemSeaIncense::
	finditem ITEM_SEA_INCENSE
	end

ChronoIsland_LostCave_Room13_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

ChronoIsland_LostCave_Room14_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

QuestIsland_SevaultCanyon_House_EventScript_ItemLuckyPunch::
	finditem ITEM_LUCKY_PUNCH
	end
