Route3_EventScript_Ben::
	end

Route3_EventScript_BenRematch::
	end

Route3_EventScript_Calvin::
	end

Route3_EventScript_CalvinRematch::
	end

Route3_EventScript_Colton::
	end

Route3_EventScript_ColtonRematch::
	end

Route3_EventScript_Greg::
	end

Route3_EventScript_GregRematch::
	end

Route3_EventScript_James::
	end

Route3_EventScript_JamesRematch::
	end

Route3_EventScript_Janice::
	end

Route3_EventScript_JaniceRematch::
	end

Route3_EventScript_Sally::
	end

Route3_EventScript_SallyRematch::
	end

Route3_EventScript_Robin::
	end

Route3_EventScript_RobinRematch::
	end

Route4_EventScript_Crissy::
	end

Route4_EventScript_CrissyRematch::
	end

Route24_EventScript_Timmy::
	end

Route24_EventScript_TimmyRematch::
	end

Route24_EventScript_Cale::
	end

Route24_EventScript_CaleRematch::
	end

Route24_EventScript_Reli::
	end

Route24_EventScript_ReliRematch::
	end

Route24_EventScript_Ali::
	end

Route24_EventScript_AliRematch::
	end

Route24_EventScript_Shane::
	end

Route24_EventScript_ShaneRematch::
	end

Route24_EventScript_Ethan::
	end

Route24_EventScript_EthanRematch::
	end

Route25_EventScript_Joey::
	end

Route25_EventScript_JoeyRematch::
	end

Route25_EventScript_Dan::
	end

Route25_EventScript_DanRematch::
	end

Route25_EventScript_Chad::
	end

Route25_EventScript_ChadRematch::
	end

Route25_EventScript_Kelsey::
	end

Route25_EventScript_KelseyRematch::
	end

Route25_EventScript_Haley::
	end

Route25_EventScript_HaleyRematch::
	end

Route25_EventScript_Franklin::
	end

Route25_EventScript_FranklinRematch::
	end

Route25_EventScript_Nob::
	end

Route25_EventScript_NobRematch::
	end

Route25_EventScript_Wayne::
	end

Route25_EventScript_WayneRematch::
	end

Route25_EventScript_Flint::
	end

Route25_EventScript_FlintRematch::
	end

Route6_EventScript_Keigo::
	end

Route6_EventScript_KeigoRematch::
	end

Route6_EventScript_Elijah::
	end

Route6_EventScript_ElijahRematch::
	end

Route6_EventScript_Ricky::
	end

Route6_EventScript_RickyRematch::
	end

Route6_EventScript_Jeff::
	end

Route6_EventScript_JeffRematch::
	end

Route6_EventScript_Nancy::
	end

Route6_EventScript_NancyRematch::
	end

Route6_EventScript_Isabelle::
	end

Route6_EventScript_IsabelleRematch::
	end

Route11_EventScript_Eddie::
	end

Route11_EventScript_EddieRematch::
	end

Route11_EventScript_Dillon::
	end

Route11_EventScript_DillonRematch::
	end

Route11_EventScript_Yasu::
	end

Route11_EventScript_YasuRematch::
	end

Route11_EventScript_Dave::
	end

Route11_EventScript_DaveRematch::
	end

Route11_EventScript_Braxton::
	end

Route11_EventScript_BraxtonRematch::
	end

Route11_EventScript_Bernie::
	end

Route11_EventScript_BernieRematch::
	end

Route11_EventScript_Hugo::
	end

Route11_EventScript_HugoRematch::
	end

Route11_EventScript_Jasper::
	end

Route11_EventScript_JasperRematch::
	end

Route11_EventScript_Dirk::
	end

Route11_EventScript_DirkRematch::
	end

Route11_EventScript_Darian::
	end

Route11_EventScript_DarianRematch::
	end

Route9_EventScript_Brent::
	end

Route9_EventScript_BrentRematch::
	end

Route9_EventScript_Conner::
	end

Route9_EventScript_ConnerRematch::
	end

Route9_EventScript_Chris::
	end

Route9_EventScript_ChrisRematch::
	end

Route9_EventScript_Drew::
	end

Route9_EventScript_DrewRematch::
	end

Route9_EventScript_Alicia::
	end

Route9_EventScript_AliciaRematch::
	end

Route9_EventScript_Caitlin::
	end

Route9_EventScript_CaitlinRematch::
	end

Route9_EventScript_Alan::
	end

Route9_EventScript_AlanRematch::
	end

Route9_EventScript_Brice::
	end

Route9_EventScript_BriceRematch::
	end

Route9_EventScript_Jeremy::
	end

Route9_EventScript_JeremyRematch::
	end

Route10_EventScript_Heidi::
	end

Route10_EventScript_HeidiRematch::
	end

Route10_EventScript_Carol::
	end

Route10_EventScript_CarolRematch::
	end

Route10_EventScript_Mark::
	end

Route10_EventScript_MarkRematch::
	end

Route10_EventScript_Herman::
	end

Route10_EventScript_HermanRematch::
	end

Route10_EventScript_Clark::
	end

Route10_EventScript_ClarkRematch::
	end

Route10_EventScript_Trent::
	end

Route10_EventScript_TrentRematch::
	end

Route8_EventScript_Paige::
	end

Route8_EventScript_PaigeRematch::
	end

Route8_EventScript_Andrea::
	end

Route8_EventScript_AndreaRematch::
	end

Route8_EventScript_Megan::
	end

Route8_EventScript_MeganRematch::
	end

Route8_EventScript_Julia::
	end

Route8_EventScript_JuliaRematch::
	end

Route8_EventScript_Aidan::
	end

Route8_EventScript_AidanRematch::
	end

Route8_EventScript_Glenn::
	end

Route8_EventScript_GlennRematch::
	end

Route8_EventScript_Leslie::
	end

Route8_EventScript_LeslieRematch::
	end

Route8_EventScript_Stan::
	end

Route8_EventScript_StanRematch::
	end

Route8_EventScript_Rich::
	end

Route8_EventScript_RichRematch::
	end

Route8_EventScript_Eli::
	end

Route8_EventScript_EliRematch::
	end

Route8_EventScript_Anne::
	end

Route8_EventScript_AnneRematch::
	end

Route8_EventScript_Ricardo::
	end

Route8_EventScript_RicardoRematch::
	end

Route8_EventScript_Jaren::
	end

Route8_EventScript_JarenRematch::
	end

Route12_EventScript_Ned::
	end

Route12_EventScript_NedRematch::
	end

Route12_EventScript_Chip::
	end

Route12_EventScript_ChipRematch::
	end

Route12_EventScript_Hank::
	end

Route12_EventScript_HankRematch::
	end

Route12_EventScript_Elliot::
	end

Route12_EventScript_ElliotRematch::
	end

Route12_EventScript_Andrew::
	end

Route12_EventScript_AndrewRematch::
	end

Route12_EventScript_Luca::
	end

Route12_EventScript_LucaRematch::
	end

Route12_EventScript_Justin::
	end

Route12_EventScript_JustinRematch::
	end

Route12_EventScript_Jes::
	end

Route12_EventScript_JesRematch::
	end

Route12_EventScript_Gia::
	end

Route12_EventScript_GiaRematch::
	end

Route13_EventScript_Jared::
	end

Route13_EventScript_JaredRematch::
	end

Route13_EventScript_Lola::
	end

Route13_EventScript_LolaRematch::
	end

Route13_EventScript_Sheila::
	end

Route13_EventScript_SheilaRematch::
	end

Route13_EventScript_Sebastian::
	end

Route13_EventScript_SebastianRematch::
	end

Route13_EventScript_Perry::
	end

Route13_EventScript_PerryRematch::
	end

Route13_EventScript_Robert::
	end

Route13_EventScript_RobertRematch::
	end

Route13_EventScript_Alma::
	end

Route13_EventScript_AlmaRematch::
	end

Route13_EventScript_Susie::
	end

Route13_EventScript_SusieRematch::
	end

Route13_EventScript_Valerie::
	end

Route13_EventScript_ValerieRematch::
	end

Route13_EventScript_Gwen::
	end

Route13_EventScript_GwenRematch::
	end

Route14_EventScript_Malik::
	end

Route14_EventScript_MalikRematch::
	end

Route14_EventScript_Lukas::
	end

Route14_EventScript_LukasRematch::
	end

Route14_EventScript_Isaac::
	end

Route14_EventScript_IsaacRematch::
	end

Route14_EventScript_Gerald::
	end

Route14_EventScript_GeraldRematch::
	end

Route14_EventScript_Donald::
	end

Route14_EventScript_DonaldRematch::
	end

Route14_EventScript_Benny::
	end

Route14_EventScript_BennyRematch::
	end

Route14_EventScript_Carter::
	end

Route14_EventScript_CarterRematch::
	end

Route14_EventScript_Mitch::
	end

Route14_EventScript_MitchRematch::
	end

Route14_EventScript_Beck::
	end

Route14_EventScript_BeckRematch::
	end

Route14_EventScript_Marlon::
	end

Route14_EventScript_MarlonRematch::
	end

Route14_EventScript_Kiri::
	end

Route14_EventScript_KiriRematch::
	end

Route14_EventScript_Jan::
	end

Route14_EventScript_JanRematch::
	end

Route15_EventScript_Ernest::
	end

Route15_EventScript_ErnestRematch::
	end

Route15_EventScript_Alex::
	end

Route15_EventScript_AlexRematch::
	end

Route15_EventScript_Grace::
	end

Route15_EventScript_GraceRematch::
	end

Route15_EventScript_Olivia::
	end

Route15_EventScript_OliviaRematch::
	end

Route15_EventScript_Edwin::
	end

Route15_EventScript_EdwinRematch::
	end

Route15_EventScript_Chester::
	end

Route15_EventScript_ChesterRematch::
	end

Route15_EventScript_Yazmin::
	end

Route15_EventScript_YazminRematch::
	end

Route15_EventScript_Kindra::
	end

Route15_EventScript_KindraRematch::
	end

Route15_EventScript_Becky::
	end

Route15_EventScript_BeckyRematch::
	end

Route15_EventScript_Celia::
	end

Route15_EventScript_CeliaRematch::
	end

Route15_EventScript_Mya::
	end

Route15_EventScript_MyaRematch::
	end

Route15_EventScript_Ron::
	end

Route15_EventScript_RonRematch::
	end

Route16_EventScript_Lao::
	end

Route16_EventScript_LaoRematch::
	end

Route16_EventScript_Hideo::
	end

Route16_EventScript_HideoRematch::
	end

Route16_EventScript_Ruben::
	end

Route16_EventScript_RubenRematch::
	end

Route16_EventScript_Koji::
	end

Route16_EventScript_KojiRematch::
	end

Route16_EventScript_Luke::
	end

Route16_EventScript_LukeRematch::
	end

Route16_EventScript_Camron::
	end

Route16_EventScript_CamronRematch::
	end

Route16_EventScript_Jed::
	end

Route16_EventScript_JedRematch::
	end

Route16_EventScript_Lea::
	end

Route16_EventScript_LeaRematch::
	end

Route17_EventScript_Billy::
	end

Route17_EventScript_BillyRematch::
	end

Route17_EventScript_Nikolas::
	end

Route17_EventScript_NikolasRematch::
	end

Route17_EventScript_Jaxon::
	end

Route17_EventScript_JaxonRematch::
	end

Route17_EventScript_William::
	end

Route17_EventScript_WilliamRematch::
	end

Route17_EventScript_Raul::
	end

Route17_EventScript_RaulRematch::
	end

Route17_EventScript_Isaiah::
	end

Route17_EventScript_IsaiahRematch::
	end

Route17_EventScript_Zeek::
	end

Route17_EventScript_ZeekRematch::
	end

Route17_EventScript_Jamal::
	end

Route17_EventScript_JamalRematch::
	end

Route17_EventScript_Corey::
	end

Route17_EventScript_CoreyRematch::
	end

Route17_EventScript_Virgil::
	end

Route17_EventScript_VirgilRematch::
	end

Route18_EventScript_Wilton::
	end

Route18_EventScript_WiltonRematch::
	end

Route18_EventScript_Ramiro::
	end

Route18_EventScript_RamiroRematch::
	end

Route18_EventScript_Jacob::
	end

Route18_EventScript_JacobRematch::
	end

Route19_EventScript_Richard::
	end

Route19_EventScript_RichardRematch::
	end

Route19_EventScript_Reece::
	end

Route19_EventScript_ReeceRematch::
	end

Route19_EventScript_Matthew::
	end

Route19_EventScript_MatthewRematch::
	end

Route19_EventScript_Douglas::
	end

Route19_EventScript_DouglasRematch::
	end

Route19_EventScript_David::
	end

Route19_EventScript_DavidRematch::
	end

Route19_EventScript_Tony::
	end

Route19_EventScript_TonyRematch::
	end

Route19_EventScript_Axle::
	end

Route19_EventScript_AxleRematch::
	end

Route19_EventScript_Anya::
	end

Route19_EventScript_AnyaRematch::
	end

Route19_EventScript_Alice::
	end

Route19_EventScript_AliceRematch::
	end

Route19_EventScript_Connie::
	end

Route19_EventScript_ConnieRematch::
	end

Route19_EventScript_Lia::
	end

Route19_EventScript_LiaRematch::
	end

Route19_EventScript_Luc::
	end

Route19_EventScript_LucRematch::
	end

Route20_EventScript_Barry::
	end

Route20_EventScript_BarryRematch::
	end

Route20_EventScript_Dean::
	end

Route20_EventScript_DeanRematch::
	end

Route20_EventScript_Darrin::
	end

Route20_EventScript_DarrinRematch::
	end

Route20_EventScript_Tiffany::
	end

Route20_EventScript_TiffanyRematch::
	end

Route20_EventScript_Nora::
	end

Route20_EventScript_NoraRematch::
	end

Route20_EventScript_Melissa::
	end

Route20_EventScript_MelissaRematch::
	end

Route20_EventScript_Shirley::
	end

Route20_EventScript_ShirleyRematch::
	end

Route20_EventScript_Roger::
	end

Route20_EventScript_RogerRematch::
	end

Route20_EventScript_Missy::
	end

Route20_EventScript_MissyRematch::
	end

Route20_EventScript_Irene::
	end

Route20_EventScript_IreneRematch::
	end

Route21_North_EventScript_Ronald::
	end

Route21_North_EventScript_RonaldRematch::
	end

Route21_South_EventScript_Claude::
	end

Route21_South_EventScript_ClaudeRematch::
	end

Route21_North_EventScript_Wade::
	end

Route21_North_EventScript_WadeRematch::
	end

Route21_South_EventScript_Nolan::
	end

Route21_South_EventScript_NolanRematch::
	end

Route21_North_EventScript_Spencer::
	end

Route21_North_EventScript_SpencerRematch::
	end

Route21_South_EventScript_Jack::
	end

Route21_South_EventScript_JackRematch::
	end

Route21_South_EventScript_Jerome::
	end

Route21_South_EventScript_JeromeRematch::
	end

Route21_South_EventScript_Roland::
	end

Route21_South_EventScript_RolandRematch::
	end

Route21_North_EventScript_Lil::
	end

Route21_North_EventScript_LilRematch::
	end

Route21_North_EventScript_Ian::
	end

Route21_North_EventScript_IanRematch::
	end

OneIsland_KindleRoad_EventScript_Maria::
	end

OneIsland_KindleRoad_EventScript_MariaRematch::
	end

OneIsland_KindleRoad_EventScript_Abigail::
	end

OneIsland_KindleRoad_EventScript_AbigailRematch::
	end

OneIsland_KindleRoad_EventScript_Finn::
	end

OneIsland_KindleRoad_EventScript_FinnRematch::
	end

OneIsland_KindleRoad_EventScript_Garrett::
	end

OneIsland_KindleRoad_EventScript_GarrettRematch::
	end

OneIsland_KindleRoad_EventScript_Tommy::
	end

OneIsland_KindleRoad_EventScript_TommyRematch::
	end

OneIsland_KindleRoad_EventScript_Sharon::
	end

OneIsland_KindleRoad_EventScript_SharonRematch::
	end

OneIsland_KindleRoad_EventScript_Tanya::
	end

OneIsland_KindleRoad_EventScript_TanyaRematch::
	end

OneIsland_KindleRoad_EventScript_Shea::
	end

OneIsland_KindleRoad_EventScript_SheaRematch::
	end

OneIsland_KindleRoad_EventScript_Hugh::
	end

OneIsland_KindleRoad_EventScript_HughRematch::
	end

OneIsland_KindleRoad_EventScript_Bryce::
	end

OneIsland_KindleRoad_EventScript_BryceRematch::
	end

OneIsland_KindleRoad_EventScript_Claire::
	end

OneIsland_KindleRoad_EventScript_ClaireRematch::
	end

OneIsland_KindleRoad_EventScript_Kia::
	end

OneIsland_KindleRoad_EventScript_KiaRematch::
	end

OneIsland_KindleRoad_EventScript_Mik::
	end

OneIsland_KindleRoad_EventScript_MikRematch::
	end

OneIsland_TreasureBeach_EventScript_Amara::
	end

OneIsland_TreasureBeach_EventScript_AmaraRematch::
	end

ThreeIsland_BondBridge_EventScript_Nikki::
	end

ThreeIsland_BondBridge_EventScript_NikkiRematch::
	end

ThreeIsland_BondBridge_EventScript_Violet::
	end

ThreeIsland_BondBridge_EventScript_VioletRematch::
	end

ThreeIsland_BondBridge_EventScript_Amira::
	end

ThreeIsland_BondBridge_EventScript_AmiraRematch::
	end

ThreeIsland_BondBridge_EventScript_Alexis::
	end

ThreeIsland_BondBridge_EventScript_AlexisRematch::
	end

ThreeIsland_BondBridge_EventScript_Tisha::
	end

ThreeIsland_BondBridge_EventScript_TishaRematch::
	end

ThreeIsland_BondBridge_EventScript_Joy::
	end

ThreeIsland_BondBridge_EventScript_JoyRematch::
	end

ThreeIsland_BondBridge_EventScript_Meg::
	end

ThreeIsland_BondBridge_EventScript_MegRematch::
	end

FiveIsland_ResortGorgeous_EventScript_Daisy::
	end

FiveIsland_ResortGorgeous_EventScript_DaisyRematch::
	end

FiveIsland_ResortGorgeous_EventScript_Celina::
	end

FiveIsland_ResortGorgeous_EventScript_CelinaRematch::
	end

FiveIsland_ResortGorgeous_EventScript_Rayna::
	end

FiveIsland_ResortGorgeous_EventScript_RaynaRematch::
	end

FiveIsland_ResortGorgeous_EventScript_Jacki::
	end

FiveIsland_ResortGorgeous_EventScript_JackiRematch::
	end

FiveIsland_ResortGorgeous_EventScript_Gillian::
	end

FiveIsland_ResortGorgeous_EventScript_GillianRematch::
	end

FiveIsland_ResortGorgeous_EventScript_Destin::
	end

FiveIsland_ResortGorgeous_EventScript_DestinRematch::
	end

FiveIsland_ResortGorgeous_EventScript_Toby::
	end

FiveIsland_ResortGorgeous_EventScript_TobyRematch::
	end

FiveIsland_WaterLabyrinth_EventScript_Alize::
	end

FiveIsland_WaterLabyrinth_EventScript_AlizeRematch::
	end

FiveIsland_MemorialPillar_EventScript_Milo::
	end

FiveIsland_MemorialPillar_EventScript_MiloRematch::
	end

FiveIsland_MemorialPillar_EventScript_Chaz::
	end

FiveIsland_MemorialPillar_EventScript_ChazRematch::
	end

FiveIsland_MemorialPillar_EventScript_Harold::
	end

FiveIsland_MemorialPillar_EventScript_HaroldRematch::
	end

SixIsland_OutcastIsland_EventScript_Tylor::
	end

SixIsland_OutcastIsland_EventScript_TylorRematch::
	end

SixIsland_OutcastIsland_EventScript_Mymo::
	end

SixIsland_OutcastIsland_EventScript_MymoRematch::
	end

SixIsland_OutcastIsland_EventScript_Nicole::
	end

SixIsland_OutcastIsland_EventScript_NicoleRematch::
	end

SixIsland_OutcastIsland_EventScript_Ava::
	end

SixIsland_OutcastIsland_EventScript_AvaRematch::
	end

SixIsland_OutcastIsland_EventScript_Geb::
	end

SixIsland_OutcastIsland_EventScript_GebRematch::
	end

SixIsland_GreenPath_EventScript_Jaclyn::
	end

SixIsland_GreenPath_EventScript_JaclynRematch::
	end

SixIsland_WaterPath_EventScript_Rose::
	end

SixIsland_WaterPath_EventScript_RoseRematch::
	end

SixIsland_WaterPath_EventScript_Edward::
	end

SixIsland_WaterPath_EventScript_EdwardRematch::
	end

SixIsland_WaterPath_EventScript_Samir::
	end

SixIsland_WaterPath_EventScript_SamirRematch::
	end

SixIsland_WaterPath_EventScript_Denise::
	end

SixIsland_WaterPath_EventScript_DeniseRematch::
	end

SixIsland_WaterPath_EventScript_Miu::
	end

SixIsland_WaterPath_EventScript_MiuRematch::
	end

SixIsland_WaterPath_EventScript_Mia::
	end

SixIsland_WaterPath_EventScript_MiaRematch::
	end

SixIsland_WaterPath_EventScript_Earl::
	end

SixIsland_WaterPath_EventScript_EarlRematch::
	end

SixIsland_RuinValley_EventScript_Stanly::
	end

SixIsland_RuinValley_EventScript_StanlyRematch::
	end

SixIsland_RuinValley_EventScript_Foster::
	end

SixIsland_RuinValley_EventScript_FosterRematch::
	end

SixIsland_RuinValley_EventScript_Larry::
	end

SixIsland_RuinValley_EventScript_LarryRematch::
	end

SixIsland_RuinValley_EventScript_Daryl::
	end

SixIsland_RuinValley_EventScript_DarylRematch::
	end

SixIsland_RuinValley_EventScript_Hector::
	end

SixIsland_RuinValley_EventScript_HectorRematch::
	end

SevenIsland_TrainerTower_EventScript_Dario::
	end

SevenIsland_TrainerTower_EventScript_DarioRematch::
	end

SevenIsland_TrainerTower_EventScript_Rodette::
	end

SevenIsland_TrainerTower_EventScript_RodetteRematch::
	end

SevenIsland_SevaultCanyon_Entrance_EventScript_Miah::
	end

SevenIsland_SevaultCanyon_Entrance_EventScript_MiahRematch::
	end

SevenIsland_SevaultCanyon_Entrance_EventScript_Eve::
	end

SevenIsland_SevaultCanyon_Entrance_EventScript_EveRematch::
	end

SevenIsland_SevaultCanyon_Entrance_EventScript_Jon::
	end

SevenIsland_SevaultCanyon_Entrance_EventScript_JonRematch::
	end

SevenIsland_SevaultCanyon_Entrance_EventScript_Mason::
	end

SevenIsland_SevaultCanyon_Entrance_EventScript_MasonRematch::
	end

SevenIsland_SevaultCanyon_Entrance_EventScript_Nicolas::
	end

SevenIsland_SevaultCanyon_Entrance_EventScript_NicolasRematch::
	end

SevenIsland_SevaultCanyon_Entrance_EventScript_Madeline::
	end

SevenIsland_SevaultCanyon_Entrance_EventScript_MadelineRematch::
	end

SevenIsland_SevaultCanyon_EventScript_Cyndy::
	end

SevenIsland_SevaultCanyon_EventScript_CyndyRematch::
	end

SevenIsland_SevaultCanyon_EventScript_Evan::
	end

SevenIsland_SevaultCanyon_EventScript_EvanRematch::
	end

SevenIsland_SevaultCanyon_EventScript_Jackson::
	end

SevenIsland_SevaultCanyon_EventScript_JacksonRematch::
	end

SevenIsland_SevaultCanyon_EventScript_Katelyn::
	end

SevenIsland_SevaultCanyon_EventScript_KatelynRematch::
	end

SevenIsland_SevaultCanyon_EventScript_Leroy::
	end

SevenIsland_SevaultCanyon_EventScript_LeroyRematch::
	end

SevenIsland_SevaultCanyon_EventScript_Michelle::
	end

SevenIsland_SevaultCanyon_EventScript_MichelleRematch::
	end

SevenIsland_SevaultCanyon_EventScript_Lex::
	end

SevenIsland_SevaultCanyon_EventScript_LexRematch::
	end

SevenIsland_SevaultCanyon_EventScript_Nya::
	end

SevenIsland_SevaultCanyon_EventScript_NyaRematch::
	end

SevenIsland_TanobyRuins_EventScript_Brandon::
	end

SevenIsland_TanobyRuins_EventScript_BrandonRematch::
	end

SevenIsland_TanobyRuins_EventScript_Benjamin::
	end

SevenIsland_TanobyRuins_EventScript_BenjaminRematch::
	end

SevenIsland_TanobyRuins_EventScript_Edna::
	end

SevenIsland_TanobyRuins_EventScript_EdnaRematch::
	end

SevenIsland_TanobyRuins_EventScript_Clifford::
	end

SevenIsland_TanobyRuins_EventScript_CliffordRematch::
	end
