FortuneIsland_WaterPath_MapScripts::
	.byte 0

FortuneIsland_WaterPath_EventScript_HornWantedSign::
	msgbox FortuneIsland_WaterPath_Text_WantedUltimateHorn, MSGBOX_SIGN
	end

FortuneIsland_WaterPath_EventScript_RouteSign::
	msgbox FortuneIsland_WaterPath_Text_RouteSign, MSGBOX_SIGN
	end
FortuneIsland_WaterPath_Text_RoseIntro::
    .string "I let a pleasant breeze lead me\n"
    .string "all the way here.$"

FortuneIsland_WaterPath_Text_RoseDefeat::
    .string "Giggle… You're so cute when you're\n"
    .string "determined.$"

FortuneIsland_WaterPath_Text_RosePostBattle::
    .string "I want to go to the woods over\n"
    .string "there, but…\p"
    .string "There are lots of BUG POKéMON.\n"
    .string "They scare me a little.$"

FortuneIsland_WaterPath_Text_EdwardIntro::
    .string "I'm practicing in secret so no one\n"
    .string "can see me.$"

FortuneIsland_WaterPath_Text_EdwardDefeat::
    .string "Nobody saw me losing, right?$"

FortuneIsland_WaterPath_Text_EdwardPostBattle::
    .string "As a performer, I don't want people\n"
    .string "to know about the effort I put in.$"

FortuneIsland_WaterPath_Text_SamirIntro::
    .string "What, you're suggesting that you're\n"
    .string "sick of seeing SWIMMERS like me?\p"
    .string "Aww, don't be hatin'!$"

FortuneIsland_WaterPath_Text_SamirDefeat::
    .string "Oh, no, no, no.$"

FortuneIsland_WaterPath_Text_SamirPostBattle::
    .string "I couldn't lift the stigma of being\n"
    .string "a SWIMMER…$"

FortuneIsland_WaterPath_Text_DeniseIntro::
    .string "My boyfriend's always busy, so I\n"
    .string "come swimming by myself.$"

FortuneIsland_WaterPath_Text_DeniseDefeat::
    .string "Awww, I knew this would happen!$"

FortuneIsland_WaterPath_Text_DenisePostBattle::
    .string "When I can't be with my boyfriend,\n"
    .string "I spend time with the POKéMON he\l"
    .string "gave me.$"

FortuneIsland_WaterPath_Text_EarlIntro::
    .string "Tell me, where are the mountains\n"
    .string "around these parts?$"

FortuneIsland_WaterPath_Text_EarlDefeat::
    .string "I lost my way while I was busy\n"
    .string "battling!$"

FortuneIsland_WaterPath_Text_EarlPostBattle::
    .string "Aren't there any mountains around\n"
    .string "these parts?$"

FortuneIsland_WaterPath_Text_MiuIntro::
    .string "MIU: Hello, POKéMON!\n"
    .string "It's time to play!$"

FortuneIsland_WaterPath_Text_MiuDefeat::
    .string "MIU: Oh, no!\n"
    .string "Mommy!$"

FortuneIsland_WaterPath_Text_MiuPostBattle::
    .string "MIU: It makes me all sad inside\n"
    .string "when we lose…$"

FortuneIsland_WaterPath_Text_MiuNotEnoughMons::
    .string "MIU: MIA and I are TWINS.\n"
    .string "We want to battle together.$"

FortuneIsland_WaterPath_Text_MiaIntro::
    .string "MIA: Hello, POKéMON!\n"
    .string "It's time to battle!$"

FortuneIsland_WaterPath_Text_MiaDefeat::
    .string "MIA: You're mean!\n"
    .string "You're bad for winning!$"

FortuneIsland_WaterPath_Text_MiaPostBattle::
    .string "MIA: Ohh…\n"
    .string "I'm sorry, my POKéMON…$"

FortuneIsland_WaterPath_Text_MiaNotEnoughMons::
    .string "MIA: Oh, you only have one\n"
    .string "POKéMON?\p"
    .string "Don't you feel lonesome?$"

FortuneIsland_WaterPath_Text_WantedUltimateHorn::
    .string "Wanted!\n"
    .string "The Ultimate Horn!$"

FortuneIsland_WaterPath_Text_RouteSign::
    .string "WATER PATH\n"
    .string "Leads to RUIN VALLEY$"

