ChronoIsland_House2_MapScripts::
	.byte 0

ChronoIsland_House2_EventScript_OldMan::
	msgbox ChronoIsland_House2_Text_MeadowBelongedToFamily, MSGBOX_NPC
	end
ChronoIsland_House2_Text_MeadowBelongedToFamily::
    .string "That MEADOW has belonged to our\n"
    .string "family for generations.\p"
    .string "I should have had a giant mansion\n"
    .string "built on it.\p"
    .string "It would be preferable to having\n"
    .string "those thugs run wild on it!$"

